export const BrandColors = {
  "500px": {
    title: "500px",
    colors: ["0099e5", "ff4c4c", "34bf49"],
    brand_url: "https://500px.com/",
  },
  "about-me": {
    title: "About.me",
    colors: ["00a98f"],
    brand_url: "https://about.me/",
  },
  adidas: {
    title: "Adidas",
    colors: [
      "000000",
      "be0027",
      "cf8d2e",
      "e4e932",
      "2c9f45",
      "371777",
      "52325d",
      "511378",
    ],
    brand_url: "https://www.adidas.com/",
  },
  adobe: {
    title: "Adobe",
    colors: [
      "ff0000",
      "fbb034",
      "ffdd00",
      "c1d82f",
      "00a4e4",
      "8a7967",
      "6a737b",
    ],
    brand_url: null,
  },
  adyen: {
    title: "Adyen",
    colors: ["0abf53", "00112c"],
    brand_url: "https://www.adyen.com/",
  },
  adzuna: {
    title: "Adzuna",
    colors: ["279b37"],
    brand_url: "https://www.adzuna.com/",
  },
  "aer-lingus": {
    title: "Aer Lingus",
    colors: ["008374", "89ba16", "fefefe"],
    brand_url: "https://www.aerlingus.com/html/home.html",
  },
  aetna: {
    title: "Aetna",
    colors: ["d20962", "f47721", "7ac143", "00a78e", "00bce4", "7d3f98"],
    brand_url: "http://www.aetna.com",
  },
  aiesec: {
    title: "AIESEC",
    colors: [
      "037ef3",
      "00c16e",
      "0cb9c1",
      "f48924",
      "f85a40",
      "ffc845",
      "52565e",
      "caccd1",
      "f3f4f7",
    ],
    brand_url: "https://www.aiesec.org/",
  },
  aim: { title: "Aim", colors: ["ffd900"], brand_url: null },
  airbnb: {
    title: "Airbnb",
    colors: ["fd5c63"],
    brand_url: "https://www.airbnb.com/",
  },
  airbus: {
    title: "Airbus",
    colors: [
      "74d2e7",
      "48a9c5",
      "0085ad",
      "8db9ca",
      "4298b5",
      "005670",
      "00205b",
      "009f4d",
      "84bd00",
      "efdf00",
      "fe5000",
      "e4002b",
      "da1884",
      "a51890",
      "0077c8",
      "008eaa",
    ],
    brand_url: "https://www.airbus.com/",
  },
  akamai: {
    title: "Akamai",
    colors: ["0099cc", "ff9933"],
    brand_url: "https://www.akamai.com",
  },
  alcon: {
    title: "Alcon",
    colors: ["0079c1", "49176d", "00a0af", "49a942"],
    brand_url: "http://www.alcon.com",
  },
  algolia: {
    title: "Algolia",
    colors: [
      "050f2c",
      "003666",
      "00aeff",
      "3369e7",
      "8e43e7",
      "b84592",
      "ff4f81",
      "ff6c5f",
      "ffc168",
      "2dde98",
      "1cc7d0",
    ],
    brand_url: "https://www.algolia.com/",
  },
  alibaba: {
    title: "Alibaba",
    colors: ["ff6a00"],
    brand_url: "https://www.alibaba.com/",
  },
  alienware: {
    title: "Alienware",
    colors: ["0c3866", "49c0b6", "222", "ce181e", "007cc0", "ffc20e"],
    brand_url: "http://www.alienware.com/",
  },
  alphabet: {
    title: "Alphabet",
    colors: ["ed1c24"],
    brand_url: "https://abc.xyz/",
  },
  amazon: { title: "Amazon", colors: ["ff9900", "146eb4"], brand_url: null },
  "american-express": {
    title: "American Express",
    colors: ["002663", "4d4f53"],
    brand_url: "https://www.americanexpress.com/",
  },
  "american-red-cross": {
    title: "American Red Cross",
    colors: [
      "ed1b2e",
      "6d6e70",
      "d7d7d8",
      "b4a996",
      "ecb731",
      "8ec06c",
      "537b35",
      "c4dff6",
      "56a0d3",
      "0091cd",
      "004b79",
      "7f181b",
      "d7d7d8",
      "9f9fa3",
      "000000",
    ],
    brand_url: "http://www.redcross.org/",
  },
  amp: {
    title: "AMP",
    colors: ["1c79c0", "0dd3ff", "0389ff"],
    brand_url: "https://www.ampproject.org/",
  },
  android: { title: "Android", colors: ["a4c639"], brand_url: null },
  "angies-list": {
    title: "Angie's List",
    colors: ["7fbb00"],
    brand_url: null,
  },
  angularjs: {
    title: "AngularJS",
    colors: ["b52e31", "000000"],
    brand_url: "https://angularjs.org/",
  },
  answers: {
    title: "Answers",
    colors: ["136ad5", "fb8a2e"],
    brand_url: "http://www.answers.com/",
  },
  aol: { title: "AOL", colors: ["ff0b00", "00c4ff"], brand_url: null },
  aparat: {
    title: "Aparat",
    colors: ["ea1d5d"],
    brand_url: "https://www.aparat.com/",
  },
  "arch-linux": {
    title: "Arch Linux",
    colors: ["1793d1", "333333"],
    brand_url: null,
  },
  "arizona-state-university-asu": {
    title: "Arizona State University",
    colors: ["990033", "ffb310"],
    brand_url: "http://www.asu.edu/",
  },
  arriva: {
    title: "Arriva",
    colors: [
      "004d73",
      "00334e",
      "007fdb",
      "dbebfa",
      "832561",
      "11862f",
      "bfca02",
      "848a8c",
    ],
    brand_url: "https://www.arrivabus.co.uk/",
  },
  "arriva-danmark": {
    title: "Arriva Danmark",
    colors: ["004d73", "00334e", "007fbd", "dbebfa"],
    brand_url: "https://arriva.dk/",
  },
  "ars-technica": {
    title: "Ars Technica",
    colors: ["ff4e00", "01cd74"],
    brand_url: "https://arstechnica.com/",
  },
  asana: {
    title: "Asana",
    colors: ["3be8b0", "1aafd0", "6a67ce", "ffb900", "fc636b"],
    brand_url: "https://asana.com/",
  },
  askfm: { title: "ASKfm", colors: ["db3552"], brand_url: "https://ask.fm/" },
  "associated-press": {
    title: "Associated Press",
    colors: ["ff322e"],
    brand_url: "http://www.ap.org/",
  },
  att: { title: "AT&T", colors: ["00a8e0"], brand_url: "http://www.att.com" },
  "atlanta-falcons": {
    title: "Atlanta Falcons",
    colors: ["000000", "a71930", "a5acaf"],
    brand_url: "http://www.atlantafalcons.com/",
  },
  "atlantic-coast-conference-acc": {
    title: "Atlantic Coast Conference",
    colors: ["013ca6", "a5a9ab"],
    brand_url: "http://www.theacc.com",
  },
  atlassian: { title: "Atlassian", colors: ["003366"], brand_url: null },
  atos: {
    title: "Atos",
    colors: [
      "0066a1",
      "231f20",
      "bfbfbf",
      "00b2a9",
      "a626aa",
      "6639b7",
      "aea400",
      "ff6319",
    ],
    brand_url: "https://atos.net/",
  },
  audi: {
    title: "Audi",
    colors: ["ffffff", "000000", "f50537"],
    brand_url: "https://www.audi.com",
  },
  auth0: {
    title: "Auth0",
    colors: ["16214d", "44c7f4", "eb5424", "d0d2d3"],
    brand_url: "https://auth0.com/",
  },
  avast: {
    title: "Avast",
    colors: ["ff7800", "2d364c", "6534ac"],
    brand_url: "https://www.avast.com/",
  },
  avira: {
    title: "Avira",
    colors: ["d40000"],
    brand_url: "https://www.avira.com/",
  },
  baidu: {
    title: "Baidu",
    colors: ["de0f17", "2529d8"],
    brand_url: "http://www.baidu.com/",
  },
  bandcamp: {
    title: "Bandcamp",
    colors: ["629aa9"],
    brand_url: "http://bandcamp.com/",
  },
  barclays: {
    title: "Barclays",
    colors: ["00aeef", "00395d"],
    brand_url: "http://www.barclays.co.uk/",
  },
  "barnes-noble": {
    title: "Barnes & Noble",
    colors: ["2a5934"],
    brand_url: "http://www.barnesandnoble.com/",
  },
  basecamp: {
    title: "Basecamp",
    colors: ["b3dcff", "5ecc62", "00ad45"],
    brand_url: "https://basecamp.com",
  },
  "beats-by-dre": {
    title: "Beats by Dre",
    colors: ["e01f3d"],
    brand_url: "https://www.beatsbydre.com/",
  },
  bebo: {
    title: "Bebo",
    colors: ["e04646"],
    brand_url: "http://www.bebo.com/",
  },
  behance: { title: "Behance", colors: ["1769ff"], brand_url: null },
  "best-buy": {
    title: "Best Buy",
    colors: ["003b64", "fff200"],
    brand_url: "http://www.bestbuy.com/",
  },
  "big-cartel": {
    title: "Big Cartel",
    colors: ["a0ac48", "70b29c"],
    brand_url: null,
  },
  bing: {
    title: "Bing",
    colors: ["ffb900", "505050", "a3a3a3"],
    brand_url: "http://www.bing.com/",
  },
  bitbucket: { title: "Bitbucket", colors: ["205081"], brand_url: null },
  bitly: { title: "bitly", colors: ["ee6123", "61b3de"], brand_url: null },
  blackberry: {
    title: "Blackberry",
    colors: [
      "005387",
      "8cb811",
      "fdb813",
      "88aca1",
      "000000",
      "788cb6",
      "a1a1a4",
      "8f8f8c",
    ],
    brand_url: "http://blackberry.com/",
  },
  blockchain: {
    title: "Blockchain",
    colors: ["123962", "2754ba", "00aee6", "799eb2", "b1d4e5"],
    brand_url: "https://www.blockchain.com/",
  },
  blogger: { title: "Blogger", colors: ["f57d00"], brand_url: null },
  boeing: {
    title: "Boeing",
    colors: ["0033a1"],
    brand_url: "http://www.boeing.com/",
  },
  "boise-state-university": {
    title: "Boise State University",
    colors: [
      "09347a",
      "007dc3",
      "0169a4",
      "3399cc",
      "f1632a",
      "464646",
      "b7b7b7",
      "f6f6f5",
    ],
    brand_url: "https://boisestate.edu/",
  },
  bombardier: {
    title: "Bombardier",
    colors: ["8996a0"],
    brand_url: "http://www.bombardier.com/",
  },
  "booking-com": {
    title: "Booking.com",
    colors: ["003580", "009fe3", "feba02", "666", "f2f6fa"],
    brand_url: "http://www.booking.com/",
  },
  booqable: {
    title: "Booqable",
    colors: ["2b80ff"],
    brand_url: "https://booqable.com/",
  },
  bower: {
    title: "Bower",
    colors: ["ffcc2f", "ef5734", "00acee", "2baf2b", "543729", "cecece"],
    brand_url: "http://bower.io/",
  },
  box: { title: "Box", colors: ["0061d5"], brand_url: "https://www.box.com/" },
  "boy-scouts-of-america": {
    title: "Boy Scouts of America",
    colors: ["ce1126", "003f87"],
    brand_url: "http://www.scouting.org/",
  },
  "british-airways": {
    title: "British Airways",
    colors: [
      "075aaa",
      "eb2226",
      "01295c",
      "efe9e5",
      "aca095",
      "b9cfed",
      "a7a9ac",
    ],
    brand_url: "http://www.britishairways.com/",
  },
  brt: {
    title: "BRT",
    colors: ["c90f23"],
    brand_url: "https://www.brt.it/en/index.do",
  },
  bt: {
    title: "BT",
    colors: ["d52685", "553a99", "6cbc35", "fd9f3e", "08538c"],
    brand_url: "http://home.bt.com/",
  },
  buffer: {
    title: "Buffer",
    colors: [
      "168eea",
      "ee4f4f",
      "fff9ea",
      "76b852",
      "323b43",
      "59626a",
      "ced7df",
      "eff3f6",
      "f4f7f9",
    ],
    brand_url: "https://bufferapp.com",
  },
  bulma: { title: "Bulma", colors: ["00d1b2"], brand_url: "https://bulma.io/" },
  "burger-king": {
    title: "Burger King",
    colors: ["ec1c24", "fdbd10", "0066b2", "ed7902"],
    brand_url: "http://www.bk.com/",
  },
  buzzfeed: {
    title: "BuzzFeed",
    colors: ["ee3322"],
    brand_url: "https://www.buzzfeed.com/",
  },
  bynder: {
    title: "Bynder",
    colors: ["00aaff"],
    brand_url: "https://www.getbynder.com/",
  },
  cadbury: {
    title: "Cadbury",
    colors: ["472f92"],
    brand_url: "https://www.cadbury.co.uk/",
  },
  canon: {
    title: "Canon",
    colors: ["bc0024", "000000"],
    brand_url: "https://www.usa.canon.com/cusa/home",
  },
  canva: {
    title: "Canva",
    colors: ["00c4cc", "6a3be4"],
    brand_url: "https://canva.com",
  },
  "capital-one": {
    title: "Capital One",
    colors: ["004977", "d03027"],
    brand_url: "https://www.capitalone.com/",
  },
  carbonmade: { title: "Carbonmade", colors: ["613854"], brand_url: null },
  carrefour: {
    title: "Carrefour",
    colors: ["00387b", "bb1e10", "f67828", "237f52"],
    brand_url: "http://www.carrefour.com/",
  },
  carrot: {
    title: "Carrot",
    colors: ["388ed1", "d74e26", "006837", "fa9f1e", "f7931e"],
    brand_url: "https://oncarrot.com/",
  },
  "cartoon-network": {
    title: "Cartoon Network",
    colors: ["00aeef", "ed008c", "fff000", "000000"],
    brand_url: "http://www.cartoonnetwork.com/",
  },
  "case-mate": {
    title: "Case-Mate",
    colors: ["84754e", "a6192e", "decba5", "000000"],
    brand_url: "http://www.case-mate.com/",
  },
  "change-org": {
    title: "Change.org",
    colors: ["ec2c22"],
    brand_url: "https://www.change.org/",
  },
  "channel-4": {
    title: "Channel 4",
    colors: [
      "2e1f54",
      "52057f",
      "bf033b",
      "f00a36",
      "ed3b21",
      "ff6908",
      "ffc719",
      "598c14",
      "335238",
      "4a8594",
      "051736",
      "000000",
      "706357",
      "b0a696",
      "dbe0e3",
      "dbeede",
    ],
    brand_url: "http://www.channel4.com/",
  },
  "charity-water": {
    title: "charity: water",
    colors: ["ffc907", "2e9df7", "231f20"],
    brand_url: "http://www.charitywater.org/",
  },
  cheddar: { title: "Cheddar", colors: ["ff7243"], brand_url: null },
  "clas-ohlson": {
    title: "Clas Ohlson",
    colors: ["60afdc"],
    brand_url: "https://www.clasohlson.com/",
  },
  "clemson-university": {
    title: "Clemson University",
    colors: [
      "f66733",
      "522d80",
      "d4c99e",
      "685c53",
      "a25016",
      "562e19",
      "86898c",
      "f9e498",
      "566127",
      "3a4958",
      "b5c327",
      "109dc0",
    ],
    brand_url: "http://www.clemson.edu/",
  },
  cloob: {
    title: "Cloob",
    colors: ["213e97", "ffac25", "d0002c", "ff4816", "ff4816"],
    brand_url: "http://www.cloob.com/",
  },
  cloudflare: {
    title: "Cloudflare",
    colors: ["f38020", "faae40", "404041"],
    brand_url: "https://www.cloudflare.com/",
  },
  cnn: {
    title: "CNN",
    colors: ["cc0000", "000000", "282828", "464646"],
    brand_url: "https://www.cnn.com",
  },
  "coca-cola": { title: "Coca-Cola", colors: ["ed1c16"], brand_url: null },
  "code-school": {
    title: "Code School",
    colors: ["616f67", "c68143"],
    brand_url: null,
  },
  codecademy: {
    title: "Codecademy",
    colors: ["f65a5b", "204056"],
    brand_url: "http://www.codecademy.com/",
  },
  codepen: {
    title: "CodePen",
    colors: ["0ebeff", "47cf73", "ae63e4", "fcd000", "ff3c41", "76daff"],
    brand_url: "http://codepen.io/",
  },
  connexxion: {
    title: "Connexxion",
    colors: ["d2ea32", "016773"],
    brand_url: "http://www.connexxion.nl/",
  },
  "constant-contact": {
    title: "Constant Contact",
    colors: ["439fd3", "f6b128"],
    brand_url: "https://www.constantcontact.com/",
  },
  "continental-ag": {
    title: "Continental AG",
    colors: [
      "ffa500",
      "00a5dc",
      "004eaf",
      "2db928",
      "057855",
      "ff2d37",
      "000000",
      "737373",
      "969696",
      "cdcdcd",
      "f0f0f0",
    ],
    brand_url: "http://www.conti-online.com/",
  },
  courtyard: {
    title: "Courtyard",
    colors: ["689550", "85c446", "c0de9e", "b9dca4"],
    brand_url: "http://courtyard.marriott.com/",
  },
  "craft-cms": {
    title: "Craft CMS",
    colors: ["da5a47"],
    brand_url: "http://buildwithcraft.com/resources",
  },
  "creative-commons": {
    title: "Creative Commons",
    colors: [
      "b62b6e",
      "9628c6",
      "4374b7",
      "abb8af",
      "98c807",
      "b1a24a",
      "edd812",
      "ef9421",
      "d13814",
    ],
    brand_url: "https://creativecommons.org/",
  },
  "creative-market": {
    title: "Creative Market",
    colors: ["8ba753"],
    brand_url: null,
  },
  crowdin: {
    title: "Crowdin",
    colors: ["30660f", "b8cc1c"],
    brand_url: "https://crowdin.com/",
  },
  "crowne-plaza": {
    title: "Crowne Plaza",
    colors: ["830051", "cf0072", "d9e506", "ff7900", "00c6d7", "766a65"],
    brand_url: "http://www.ihg.com/crowneplaza",
  },
  crunchbase: {
    title: "CrunchBase",
    colors: ["2292a7"],
    brand_url: "https://www.crunchbase.com/",
  },
  culvers: {
    title: "Culver's",
    colors: ["005696"],
    brand_url: "http://www.culvers.com/",
  },
  cunard: {
    title: "Cunard",
    colors: ["1d1d1b", "ae9a64", "e42313", "8b8c8d"],
    brand_url: "http://www.cunard.com/",
  },
  cvs: { title: "CVS", colors: ["cc0000"], brand_url: "http://www.cvs.com/" },
  dailymotion: {
    title: "Dailymotion",
    colors: ["00aaff", "00d2f3"],
    brand_url: "http://www.dailymotion.com/",
  },
  daimler: {
    title: "Daimler",
    colors: ["263f6a", "182b45", "6b0f24", "193725", "606061"],
    brand_url: "https://www.daimler.com/",
  },
  datadog: {
    title: "Datadog",
    colors: ["774aa4"],
    brand_url: "https://www.datadoghq.com/",
  },
  dealhack: {
    title: "Dealhack",
    colors: ["095280", "00a1f1"],
    brand_url: "https://dealhack.com/",
  },
  debian: {
    title: "Debian",
    colors: ["a80030"],
    brand_url: "https://www.debian.org/",
  },
  deezer: {
    title: "Deezer",
    colors: [
      "ff0000",
      "ffed00",
      "ff0092",
      "c2ff00",
      "00c7f2",
      "c1f1fc",
      "ebffac",
      "ffc2e5",
      "ffaaaa",
    ],
    brand_url: "https://www.deezer.com/",
  },
  delectable: {
    title: "Delectable",
    colors: [
      "334858",
      "cd595a",
      "94938f",
      "a3a7a6",
      "dbc5b0",
      "f8dfc2",
      "f9ebdf",
    ],
    brand_url: "https://delectable.com/",
  },
  delicious: {
    title: "Delicious",
    colors: ["3399ff", "222222", "eeeeee"],
    brand_url: null,
  },
  deliveroo: {
    title: "Deliveroo",
    colors: ["00c1b2"],
    brand_url: "https://deliveroo.co.uk",
  },
  dell: {
    title: "Dell",
    colors: [
      "0085c3",
      "7ab800",
      "f2af00",
      "dc5034",
      "ce1126",
      "b7295a",
      "6e2585",
      "71c6c1",
      "5482ab",
      "009bbb",
      "444444",
      "eeeeee",
    ],
    brand_url: null,
  },
  "delta-airlines": {
    title: "Delta Airlines",
    colors: ["c8102e", "862633", "003a70"],
    brand_url: "https://www.delta.com/",
  },
  "dental-plans": {
    title: "Dental Plans",
    colors: ["f99104", "00b7c9"],
    brand_url: "http://www.dentalplans.com/",
  },
  "designer-news": {
    title: "Designer News",
    colors: ["2d72d9"],
    brand_url: null,
  },
  designmoo: {
    title: "Designmoo",
    colors: ["e64b50", "dbc65d"],
    brand_url: null,
  },
  "deutsche-bahn": {
    title: "Deutsche Bahn",
    colors: ["ff0000"],
    brand_url: "http://www.deutschebahn.com/",
  },
  deviantart: {
    title: "DeviantArt",
    colors: ["05cc47", "4dc47d", "181a1b"],
    brand_url: "http://www.deviantart.com/",
  },
  devour: { title: "Devour", colors: ["ff0000"], brand_url: null },
  dewalt: { title: "DEWALT", colors: ["febd17"], brand_url: null },
  dhl: {
    title: "DHL",
    colors: ["ba0c2f", "ffcd00", "c9c9c9"],
    brand_url: "http://www.dhl.com/",
  },
  diebold: {
    title: "Diebold",
    colors: ["007dc3", "003f69", "954010", "445c6e", "005238", "97824b"],
    brand_url: "http://www.diebold.com/",
  },
  digg: {
    title: "Digg",
    colors: ["005be2", "000000"],
    brand_url: "http://digg.com/",
  },
  "digital-ocean": {
    title: "Digital Ocean",
    colors: ["008bcf"],
    brand_url: "https://www.digitalocean.com/",
  },
  dindr: {
    title: "Dindr",
    colors: [
      "fdb94e",
      "f9a852",
      "f69653",
      "f38654",
      "f07654",
      "ed6856",
      "ef5956",
      "ee4c58",
      "56c1ab",
      "6a6b6a",
    ],
    brand_url: "http://dindrapp.com/",
  },
  "direct-energy": {
    title: "Direct Energy",
    colors: ["f05d21", "2c5770", "0f723a", "c7c8ca", "666666"],
    brand_url: "https://www.directenergy.com/",
  },
  directv: {
    title: "DIRECTV",
    colors: ["00a6d6", "00629b", "003865"],
    brand_url: "http://www.directv.com/",
  },
  discogs: {
    title: "Discogs",
    colors: ["000000", "333333", "f5df2e"],
    brand_url: "https://www.discogs.com/",
  },
  discord: {
    title: "Discord",
    colors: ["7289da", "99aab5", "2c2f33", "23272a"],
    brand_url: "https://discordapp.com/",
  },
  "dish-network": {
    title: "DISH Network",
    colors: ["ec1944"],
    brand_url: "http://www.dish.com/",
  },
  "disney-xd": {
    title: "Disney XD",
    colors: ["0af167", "ee70a6", "520099", "39eafd", "0d0735", "f5f5f5"],
    brand_url: "http://disneyxd.disney.com/",
  },
  disqus: { title: "Disqus", colors: ["2e9fff"], brand_url: null },
  django: { title: "Django", colors: ["092e20"], brand_url: null },
  docker: {
    title: "Docker",
    colors: ["0db7ed", "384d54"],
    brand_url: "https://www.docker.com/",
  },
  dominos: {
    title: "Domino's",
    colors: ["0b648f", "e21737"],
    brand_url: "https://dominos.com/",
  },
  dow: {
    title: "DOW",
    colors: [
      "e80033",
      "fdbb30",
      "ed8b00",
      "f15d22",
      "bf0d3e",
      "910048",
      "d0006f",
    ],
    brand_url: "http://www.dow.com/",
  },
  dribbble: {
    title: "Dribbble",
    colors: ["444444", "ea4c89", "8aba56", "ff8833", "00b6e3", "9ba5a8"],
    brand_url: null,
  },
  dropbox: {
    title: "Dropbox",
    colors: ["007ee5", "7b8994", "47525d", "3d464d"],
    brand_url: null,
  },
  droplr: {
    title: "Droplr",
    colors: ["5654a4"],
    brand_url: "http://droplr.com/",
  },
  drupal: {
    title: "Drupal",
    colors: ["0077c0", "81ceff", "00598e"],
    brand_url: null,
  },
  "duke-university": {
    title: "Duke University",
    colors: ["001a57", "003366"],
    brand_url: "https://www.duke.edu/",
  },
  dunked: {
    title: "Dunked",
    colors: ["2da9d7", "212a3e"],
    brand_url: "http://dunked.com/",
  },
  duolingo: {
    title: "Duolingo",
    colors: [
      "7ac70c",
      "8ee000",
      "faa918",
      "ffc715",
      "d33131",
      "e53838",
      "1cb0f6",
      "14d4f4",
      "8549ba",
      "a560e8",
      "4c4c4c",
      "6f6f6f",
      "cfcfcf",
      "f0f0f0",
      "bff199",
      "f7c8c9",
    ],
    brand_url: "https://www.duolingo.com/",
  },
  dwolla: {
    title: "Dwolla",
    colors: ["ff7404"],
    brand_url: "https://www.dwolla.com/",
  },
  etrade: {
    title: "E*TRADE",
    colors: ["6633cc", "99cc00"],
    brand_url: "https://etrade.com/",
  },
  e4: {
    title: "E4",
    colors: ["6d1d7c"],
    brand_url: "http://www.channel4.com/e4/",
  },
  "easy-jet": {
    title: "Easy Jet",
    colors: ["ff6600", "000000", "58595b"],
    brand_url: "http://www.easyjet.com/",
  },
  ebay: {
    title: "eBay",
    colors: ["e53238", "0064d2", "f5af02", "86b817"],
    brand_url: null,
  },
  "el-al": {
    title: "El Al",
    colors: ["131137", "918978"],
    brand_url: "http://www.elal.com/",
  },
  elance: {
    title: "Elance",
    colors: ["0d69af"],
    brand_url: "https://www.elance.com/",
  },
  ello: { title: "Ello", colors: ["000000"], brand_url: "https://ello.co/" },
  ember: {
    title: "Ember",
    colors: ["f23819"],
    brand_url: "http://emberjs.com/",
  },
  emma: {
    title: "Emma",
    colors: ["314855", "5cc3e8", "ffdb00", "79ceb8", "e95f5c"],
    brand_url: "http://myemma.com/",
  },
  endomundo: {
    title: "Endomundo",
    colors: ["87aa14"],
    brand_url: "https://www.endomondo.com/",
  },
  engadget: { title: "Engadget", colors: ["40b3ff"], brand_url: null },
  envato: { title: "Envato", colors: ["82b541"], brand_url: null },
  epam: {
    title: "EPAM",
    colors: ["39c2d7", "a3c644", "464547", "b22746", "8e244d"],
    brand_url: "https://www.epam.com/",
  },
  epictions: {
    title: "Epictions",
    colors: ["ff2052", "e6e6e6", "404040", "01b5dd", "b0db64"],
    brand_url: "http://www.epictions.com/",
  },
  ericsson: {
    title: "Ericsson",
    colors: ["002561"],
    brand_url: "http://www.ericsson.com",
  },
  esl: {
    title: "ESL",
    colors: ["0d9ddb", "48b8e7", "efecea", "2c2b2b"],
    brand_url: "http://www.turtle-entertainment.com/",
  },
  espn: { title: "ESPN", colors: ["ff0033"], brand_url: null },
  estimote: {
    title: "Estimote",
    colors: ["6a9c84", "790f59", "373b9c", "f784b6", "39b7dd", "ccc900"],
    brand_url: "https://estimote.com/",
  },
  etsy: { title: "Etsy", colors: ["d5641c"], brand_url: null },
  evaneos: {
    title: "Evaneos",
    colors: ["33cc99", "4ba6f5", "fdca30", "f79400", "f34235"],
    brand_url: "http://www.evaneos.com/",
  },
  eventbrite: {
    title: "Eventbrite",
    colors: ["ff8000"],
    brand_url: "https://www.eventbrite.com/",
  },
  evernote: {
    title: "Evernote",
    colors: [
      "2dbe60",
      "7b868a",
      "2facb2",
      "166a8f",
      "3b4446",
      "525e61",
      "7b868a",
      "aeb6b8",
      "d7dcdd",
      "eff2f3",
    ],
    brand_url: "https://evernote.com/",
  },
  execucar: {
    title: "ExecuCar",
    colors: ["203143", "da9a39"],
    brand_url: "https://www.execucar.com/",
  },
  eztalks: {
    title: "ezTalks",
    colors: ["00a0e9"],
    brand_url: "https://www.eztalks.com/",
  },
  "fab-com": {
    title: "Fab.com",
    colors: ["dd0017", "000000"],
    brand_url: null,
  },
  facebook: { title: "Facebook", colors: ["3b5998"], brand_url: null },
  "fairfield-inn-suites": {
    title: "Fairfield Inn &amp; Suites",
    colors: ["6caddf", "b06010", "004990", "b50938"],
    brand_url: "http://www.marriott.com/fairfield-inn/travel.mi",
  },
  fairmont: {
    title: "Fairmont",
    colors: ["a6a685", "000000"],
    brand_url: "http://www.fairmont.com/",
  },
  "famo-us": {
    title: "famo.us",
    colors: ["fa5c4f", "333333"],
    brand_url: "http://famo.us/",
  },
  fancy: {
    title: "Fancy",
    colors: ["3098dc", "494e58"],
    brand_url: "https://fancy.com",
  },
  fedex: {
    title: "Fedex",
    colors: ["4d148c", "ff6600"],
    brand_url: "http://www.fedex.com/",
  },
  feedly: {
    title: "Feedly",
    colors: ["2bb24c"],
    brand_url: "http://feedly.com/",
  },
  fendi: {
    title: "Fendi",
    colors: ["f9b949"],
    brand_url: "https://www.fendi.com/",
  },
  ferrari: {
    title: "Ferrari",
    colors: ["e32119"],
    brand_url: "http://www.ferrari.com/",
  },
  fiat: {
    title: "Fiat",
    colors: ["96172e", "6d2d41"],
    brand_url: "http://www.fiat.com",
  },
  film4: {
    title: "Film4",
    colors: ["000000", "d6182a"],
    brand_url: "http://www.channel4.com/channel/film4",
  },
  firefox: {
    title: "Firefox",
    colors: [
      "e66000",
      "ff9500",
      "ffcb00",
      "00539f",
      "0095dd",
      "331e54",
      "002147",
    ],
    brand_url: null,
  },
  fiskars: {
    title: "Fiskars",
    colors: ["ff8e00", "000000", "955214", "55601c", "005172"],
    brand_url: "http://www.fiskars.com",
  },
  fitbit: {
    title: "Fitbit",
    colors: ["4cc2c4", "f54785", "343434"],
    brand_url: "http://www.fitbit.com/",
  },
  "five-guys": {
    title: "Five Guys",
    colors: ["ed174f", "fbb040", "efc402", "d4891c"],
    brand_url: "http://www.fiveguys.com/",
  },
  fiverr: {
    title: "Fiverr",
    colors: ["00b22d"],
    brand_url: "https://www.fiverr.com/",
  },
  fivethirtyeight: {
    title: "FiveThirtyEight",
    colors: ["ed713a", "000000"],
    brand_url: "http://fivethirtyeight.com/",
  },
  flattr: { title: "Flattr", colors: ["f67c1a", "338d11"], brand_url: null },
  "flavors-me": {
    title: "Flavors.me",
    colors: ["f10087", "009ae7"],
    brand_url: "http://flavors.me/",
  },
  flickr: { title: "Flickr", colors: ["0063dc", "ff0084"], brand_url: null },
  flipboard: {
    title: "Flipboard",
    colors: ["e12828"],
    brand_url: "https://flipboard.com/",
  },
  flixster: {
    title: "Flixster",
    colors: ["2971b2"],
    brand_url: "http://www.flixster.com/",
  },
  "fluid-ui": {
    title: "Fluid UI",
    colors: ["3fa9f5", "989898", "f8f8f8"],
    brand_url: "https://www.fluidui.com/",
  },
  follr: {
    title: "Follr",
    colors: ["4dc9f6", "f67019", "f53794", "537bc4", "acc236"],
    brand_url: "http://www.follr.com/",
  },
  fontawesome: {
    title: "FontAwesome",
    colors: ["228ae6"],
    brand_url: "https://fontawesome.com/",
  },
  ford: {
    title: "Ford",
    colors: ["1c396d"],
    brand_url: "http://www.ford.com/",
  },
  "4ormat": {
    title: "Format",
    colors: ["ee3440"],
    brand_url: "http://format.com/",
  },
  forrst: { title: "Forrst", colors: ["5b9a68"], brand_url: null },
  foursquare: {
    title: "Foursquare",
    colors: ["f94877", "0732a2", "2d5be3"],
    brand_url: "https://foursquare.com/",
  },
  freecodecamp: {
    title: "FreeCodeCamp",
    colors: ["006400", "ff9c2a", "ff4025", "3949ab", "efefef"],
    brand_url: "https://www.freecodecamp.com/",
  },
  friend2friend: {
    title: "Friend2Friend",
    colors: ["0f99d6"],
    brand_url: "http://www.friend2friend.com/",
  },
  "gallaudet-university": {
    title: "Gallaudet University",
    colors: ["00457c", "e8d4a2"],
    brand_url: "http://www2.gallaudet.edu/",
  },
  gannett: {
    title: "Gannett",
    colors: ["009bff"],
    brand_url: "http://www.gannett.com/",
  },
  garmin: { title: "Garmin", colors: ["007cc3"], brand_url: null },
  garuda: {
    title: "Garuda",
    colors: ["484848", "002561", "2f6f7e"],
    brand_url: "https://www.garuda-indonesia.com/",
  },
  generatepress: {
    title: "GeneratePress",
    colors: ["1b212b", "1e72bd", "efefef"],
    brand_url: "https://generatepress.com/",
  },
  geocaching: { title: "Geocaching", colors: ["4a742c"], brand_url: null },
  "georgia-southern-university": {
    title: "Georgia Southern University",
    colors: ["041e42", "a99260"],
    brand_url: "http://www.georgiasouthern.edu/",
  },
  ghost: {
    title: "Ghost",
    colors: ["212425", "718087", "5ba4e5", "9fbb58", "e9e8dd"],
    brand_url: null,
  },
  gibson: {
    title: "Gibson",
    colors: ["000000", "436f8e", "887d59", "8f9696"],
    brand_url: "http://www.gibson.com/",
  },
  gimmebar: { title: "Gimmebar", colors: ["d6156c"], brand_url: null },
  github: {
    title: "GitHub",
    colors: [
      "4078c0",
      "6cc644",
      "bd2c00",
      "c9510c",
      "6e5494",
      "fafafa",
      "f5f5f5",
      "333",
    ],
    brand_url: "https://github.com/",
  },
  gitlab: {
    title: "GitLab",
    colors: ["fca326", "fc6d26", "e24329", "554488"],
    brand_url: "https://gitlab.com",
  },
  gitter: {
    title: "Gitter",
    colors: ["46bc99", "f68d42", "ed1965", "f2f0ed", "3a3133"],
    brand_url: "https://gitter.im/",
  },
  gittip: { title: "Gittip", colors: ["663300", "339966"], brand_url: null },
  glaxosmithkline: {
    title: "GlaxoSmithKline",
    colors: ["f36f21", "72635c", "aca6a2", "ffffff"],
    brand_url: "https://www.gsk.com/",
  },
  godaddy: { title: "GoDaddy", colors: ["7db701", "ff8a00"], brand_url: null },
  gogo: {
    title: "Gogo",
    colors: ["e80029", "40b4e5", "7c868d"],
    brand_url: "https://www.gogoair.com/",
  },
  goodreads: {
    title: "Goodreads",
    colors: ["553b08"],
    brand_url: "http://www.goodreads.com/",
  },
  google: {
    title: "Google",
    colors: ["4285f4", "34a853", "fbbc05", "ea4335"],
    brand_url: "https://www.google.com/",
  },
  "google-allo": {
    title: "Google Allo",
    colors: ["fbbc05"],
    brand_url: "https://allo.google.com/",
  },
  "google-duo": {
    title: "Google Duo",
    colors: ["4285f4"],
    brand_url: "https://duo.google.com/",
  },
  "google-plus": {
    title: "Google+",
    colors: ["dd4b39"],
    brand_url: "https://plus.google.com/",
  },
  "gospel-for-asia": {
    title: "Gospel for Asia",
    colors: ["099d84", "4d9db3", "456acf", "8762c9", "ad182d", "e15f5f"],
    brand_url: "https://www.gfa.org/",
  },
  gravatar: {
    title: "Gravatar",
    colors: ["1e8cbe"],
    brand_url: "http://gravatar.com/",
  },
  gravit: {
    title: "Gravit",
    colors: ["e30061", "d5df00", "475258"],
    brand_url: "http://about.gravit.io/",
  },
  gwr: {
    title: "Great Western Railway (GWR)",
    colors: ["0b2d27", "000000", "ffffff"],
    brand_url: "https://www.gwr.com",
  },
  greenhouse: {
    title: "Greenhouse",
    colors: ["00b2a9"],
    brand_url: "https://www.greenhouse.io/",
  },
  groupon: { title: "Groupon", colors: ["82b548"], brand_url: null },
  grunt: {
    title: "Grunt",
    colors: ["fba919", "463014"],
    brand_url: "http://gruntjs.com/",
  },
  gumtree: {
    title: "Gumtree",
    colors: ["72ef36", "3b3141", "f0ece6"],
    brand_url: "https://www.gumtree.com/",
  },
  gvb: {
    title: "GVB",
    colors: [
      "0863b5",
      "fec600",
      "f39100",
      "e3001f",
      "e50064",
      "954a97",
      "009ee3",
      "13a538",
    ],
    brand_url: "http://gvb.nl/",
  },
  "hacker-news": {
    title: "Hacker News",
    colors: ["ff4000"],
    brand_url: "https://news.ycombinator.com/",
  },
  hangouts: {
    title: "Hangouts",
    colors: ["0f9d58"],
    brand_url: "https://hangouts.google.com/",
  },
  happn: {
    title: "happn",
    colors: ["0087b4"],
    brand_url: "https://www.happn.com/",
  },
  heineken: {
    title: "Heineken",
    colors: ["008200", "205527", "ff2b00", "c3c3c3"],
    brand_url: "https://www.heineken.com/",
  },
  hellowallet: { title: "HelloWallet", colors: ["0093d0"], brand_url: null },
  "help-scout": {
    title: "Help Scout",
    colors: ["3197d6", "394956", "d6dde3"],
    brand_url: "https://www.helpscout.net/",
  },
  heroku: { title: "Heroku", colors: ["c9c3e6", "6762a6"], brand_url: null },
  "hewlett-packard-enterprise": {
    title: "Hewlett Packard Enterprise",
    colors: ["00b388", "425563"],
    brand_url: "https://www.hpe.com/",
  },
  hi5: { title: "hi5", colors: ["fd9827"], brand_url: "http://www.hi5.com/" },
  highfive: {
    title: "Highfive",
    colors: ["a26eea", "f7afff", "5d70ea", "46b7fd"],
    brand_url: "https://highfive.com/",
  },
  "home-depot": {
    title: "Home Depot",
    colors: ["f96302"],
    brand_url: "http://www.homedepot.com/",
  },
  homeaway: {
    title: "HomeAway",
    colors: ["2a6ebb", "ff8a00"],
    brand_url: "http://www.homeaway.com/",
  },
  hootsuite: {
    title: "HootSuite",
    colors: [
      "003265",
      "f7e8d5",
      "ffbd0a",
      "c6af92",
      "71685f",
      "54493f",
      "38322d",
    ],
    brand_url: null,
  },
  houzz: { title: "Houzz", colors: ["7ac142", "000000"], brand_url: null },
  hp: { title: "HP", colors: ["0096d6", "d7410b"], brand_url: null },
  hsbc: { title: "HSBC", colors: ["db0011"], brand_url: null },
  html5: { title: "HTML5", colors: ["e34f26"], brand_url: null },
  hulu: {
    title: "Hulu",
    colors: ["66aa33", "99cc33", "41811e", "222222", "666666", "e8e8e8"],
    brand_url: "https://www.hulu.com",
  },
  "humble-bundle": {
    title: "Humble Bundle",
    colors: ["cb272c"],
    brand_url: "https://www.humblebundle.com/",
  },
  hyatt: {
    title: "Hyatt",
    colors: ["6d6e71", "bf5b20", "006e96", "8c8700", "ad5f7d", "d79100"],
    brand_url: "http://www.hyatt.com/",
  },
  ibm: { title: "IBM", colors: ["006699"], brand_url: null },
  icons8: {
    title: "Icons8",
    colors: ["32c24d"],
    brand_url: "https://icons8.com/",
  },
  ideal: {
    title: "iDEAL",
    colors: ["cc0066", "79afc1", "000000"],
    brand_url: "https://www.ideal.nl/",
  },
  "identi-ca": {
    title: "Identi.ca",
    colors: ["789240", "7d0100", "8baaff"],
    brand_url: null,
  },
  ifttt: {
    title: "IFTTT",
    colors: ["33ccff", "ff4400", "000000"],
    brand_url: "https://ifttt.com/",
  },
  iheartradio: {
    title: "iHeartRadio",
    colors: ["c6002b"],
    brand_url: "http://www.iheart.com/",
  },
  ikea: { title: "IKEA", colors: ["ffcc00", "003399"], brand_url: null },
  imdb: { title: "IMDb", colors: ["f5de50"], brand_url: null },
  imgur: { title: "Imgur", colors: ["85bf25"], brand_url: "http://imgur.com/" },
  indeed: {
    title: "Indeed",
    colors: ["2164f4", "ff6600"],
    brand_url: "http://www.indeed.com/",
  },
  indiegogo: {
    title: "Indiegogo",
    colors: ["eb1478"],
    brand_url: "https://www.indiegogo.com/",
  },
  ing: {
    title: "ING",
    colors: ["ff6200", "000066"],
    brand_url: "https://ing.com",
  },
  instacart: {
    title: "Instacart",
    colors: ["60ab59"],
    brand_url: "https://www.instacart.com/",
  },
  instagram: {
    title: "Instagram",
    colors: [
      "405de6",
      "5851db",
      "833ab4",
      "c13584",
      "e1306c",
      "fd1d1d",
      "f56040",
      "f77737",
      "fcaf45",
      "ffdc80",
    ],
    brand_url: "https://www.instagram.com/",
  },
  instapage: {
    title: "Instapage",
    colors: ["0d1a2b", "1565c0", "1e88e5", "bcced6", "f2f7f9"],
    brand_url: "https://instapage.com/",
  },
  instapaper: {
    title: "Instapaper",
    colors: ["000000", "428bca"],
    brand_url: null,
  },
  intel: { title: "Intel", colors: ["0f7dc2"], brand_url: null },
  "internet-society": {
    title: "Internet Society",
    colors: [
      "0c1c2c",
      "3a82e4",
      "40b2a4",
      "eff2ec",
      "dedad0",
      "d0e6da",
      "085856",
      "24366e",
      "143e50",
      "7e245c",
      "d25238",
      "eeca4a",
    ],
    brand_url: "https://www.internetsociety.org/",
  },
  intuit: { title: "Intuit", colors: ["365ebf"], brand_url: null },
  invision: {
    title: "InVision",
    colors: [
      "ff3366",
      "252b33",
      "2f7bbd",
      "323a45",
      "8a959e",
      "d4d7da",
      "e9ebec",
    ],
    brand_url: "https://www.invisionapp.com",
  },
  ios: {
    title: "iOS",
    colors: [
      "5fc9f8",
      "fecb2e",
      "fd9426",
      "fc3158",
      "147efb",
      "53d769",
      "fc3d39",
      "8e8e93",
    ],
    brand_url: "https://www.apple.com/ios/",
  },
  "israel-railways": {
    title: "Israel Railways",
    colors: ["1e1f56"],
    brand_url: "https://www.rail.co.il/",
  },
  issuu: {
    title: "Issuu",
    colors: ["f36d5d"],
    brand_url: "https://issuu.com/",
  },
  istock: {
    title: "iStock",
    colors: ["fe423f", "02a388", "0c0d0d", "e8eded", "dce1e1"],
    brand_url: "http://www.istockphoto.com/",
  },
  javascript: { title: "JavaScript", colors: ["f7df1e"], brand_url: null },
  jawbone: {
    title: "Jawbone",
    colors: ["000000"],
    brand_url: "https://jawbone.com/",
  },
  jbl: { title: "JBL", colors: ["ff6600"], brand_url: "http://www.jbl.com/" },
  jetpack: {
    title: "Jetpack",
    colors: ["669c34", "72af3a"],
    brand_url: "https://jetpack.com/",
  },
  joomla: {
    title: "Joomla!",
    colors: ["f44321", "5091cd", "f9a541", "7ac143"],
    brand_url: "https://www.joomla.org/",
  },
  joyent: {
    title: "Joyent",
    colors: ["ff6600"],
    brand_url: "https://www.joyent.com/",
  },
  jquery: {
    title: "jQuery",
    colors: ["0769ad", "7acef4"],
    brand_url: "https://jquery.com/",
  },
  "kaspersky-lab": {
    title: "Kaspersky Lab",
    colors: ["006c54", "d52a1d"],
    brand_url: "http://www.kaspersky.com/",
  },
  keeeb: {
    title: "Keeeb",
    colors: ["00a9c0"],
    brand_url: "http://www.keeeb.com/",
  },
  "khan-academy": {
    title: "Khan Academy",
    colors: ["9cb443", "242f3a"],
    brand_url: "https://www.khanacademy.org/",
  },
  kia: { title: "Kia", colors: ["c21a30"], brand_url: "http://www.kia.com/" },
  kickstarter: {
    title: "Kickstarter",
    colors: ["2bde73", "0f2105"],
    brand_url: null,
  },
  kik: {
    title: "kik",
    colors: ["82bc23", "3db4e7"],
    brand_url: "http://www.kik.com/",
  },
  kippt: { title: "kippt", colors: ["d51007"], brand_url: null },
  kitkat: {
    title: "KITKAT",
    colors: ["d70021"],
    brand_url: "https://www.kitkat.com/",
  },
  kiva: {
    title: "Kiva",
    colors: ["63a541", "236133", "26b6e8"],
    brand_url: "https://www.kiva.org/",
  },
  kiwipay: { title: "Kiwipay", colors: ["00b0df"], brand_url: null },
  klm: { title: "KLM", colors: ["00a1e4"], brand_url: "https://www.klm.com/" },
  "knight-foundation": {
    title: "Knight Foundation",
    colors: [
      "000000",
      "03cce6",
      "29c876",
      "ff4081",
      "fdce2e",
      "f5f4f2",
      "cccccc",
      "666666",
      "ff3939",
    ],
    brand_url: "https://knightfoundation.org/",
  },
  lamborghini: {
    title: "Lamborghini",
    colors: ["ddb321"],
    brand_url: "https://www.lamborghini.com/",
  },
  laravel: {
    title: "Laravel",
    colors: ["f55247"],
    brand_url: "http://laravel.com/",
  },
  lastfm: {
    title: "LastFM",
    colors: ["d51007"],
    brand_url: "http://www.last.fm/",
  },
  lastpass: {
    title: "LastPass",
    colors: [
      "d32d27",
      "af0809",
      "000000",
      "0c2340",
      "00a3e0",
      "ede04b",
      "333f48",
      "d9e1e2",
    ],
    brand_url: "https://www.lastpass.com/",
  },
  lego: {
    title: "LEGO",
    colors: ["f6ec35", "d11013", "000000"],
    brand_url: "https://www.lego.com/",
  },
  line: { title: "LINE", colors: ["00c300"], brand_url: "http://line.me/" },
  linkedin: {
    title: "LinkedIn",
    colors: [
      "0077b5",
      "000000",
      "313335",
      "86888a",
      "caccce",
      "00a0dc",
      "8d6cab",
      "dd5143",
      "e68523",
    ],
    brand_url: "https://www.linkedin.com/",
  },
  livestream: {
    title: "Livestream",
    colors: [
      "cf202e",
      "232121",
      "f78822",
      "f6db35",
      "6dc067",
      "4185be",
      "8f499c",
    ],
    brand_url: null,
  },
  lloyds: {
    title: "Lloyd's",
    colors: [
      "d81f2a",
      "ff9900",
      "e0d86e",
      "9ea900",
      "6ec9e0",
      "007ea3",
      "9e4770",
      "631d76",
      "1e1e1e",
    ],
    brand_url: "http://www.lloyds.com/",
  },
  "localbitcoins-com": {
    title: "LocalBitcoins.com",
    colors: ["006fbf", "ff7b00"],
    brand_url: "https://localbitcoins.com/",
  },
  "login-radius": {
    title: "LoginRadius",
    colors: ["008ecf", "09263c", "020b13", "e3f1f8", "073857"],
    brand_url: "https://www.loginradius.com/",
  },
  lomo: {
    title: "LOMO",
    colors: ["eb0028", "00a0df"],
    brand_url: "http://www.lomography.com/",
  },
  "london-underground": {
    title: "London Underground",
    colors: ["000099", "cc3333"],
    brand_url: "https://tfl.gov.uk/modes/tube/",
  },
  lowes: {
    title: "Lowe's",
    colors: ["004990", "15b6e5"],
    brand_url: "https://www.lowes.com/",
  },
  lumo: { title: "Lumo", colors: ["576396"], brand_url: null },
  lyft: {
    title: "Lyft",
    colors: ["ff00bf", "352384", "333447", "f3f3f5"],
    brand_url: "https://www.lyft.com/",
  },
  magento: {
    title: "Magento",
    colors: ["f46f25"],
    brand_url: "https://magento.com/",
  },
  "mail-ru": {
    title: "Mail.Ru",
    colors: ["168de2", "ffa930"],
    brand_url: "https://mail.ru/",
  },
  mailchimp: {
    title: "MailChimp",
    colors: ["239ab9", "52bad5", "6dc5dc", "373737", "5d5c5d", "b7b7b7"],
    brand_url: "http://mailchimp.com/",
  },
  "manjaro-linux": {
    title: "Manjaro Linux",
    colors: ["34be5b"],
    brand_url: "https://manjaro.org/",
  },
  mapbox: {
    title: "Mapbox",
    colors: [
      "3bb2d0",
      "3887be",
      "8a8acb",
      "56b881",
      "50667f",
      "41afa5",
      "f9886c",
      "e55e5e",
      "ed6498",
      "fbb03b",
      "142736",
      "28353d",
      "222b30",
    ],
    brand_url: "https://www.mapbox.com/",
  },
  "massachusetts-institute-of-technology": {
    title: "Massachusetts Institute of Technology",
    colors: ["a31f34", "8a8b8c", "c2c0bf"],
    brand_url: "http://web.mit.edu/",
  },
  "massy-group": {
    title: "Massy Group",
    colors: ["004a77", "00adee", "ff8100", "ffd200"],
    brand_url: "http://www.massygroup.com/home.aspx",
  },
  mastercard: {
    title: "Mastercard",
    colors: ["cc0000", "ff9900", "000066"],
    brand_url: "http://www.mastercard.us/",
  },
  mcdonalds: {
    title: "McDonald's",
    colors: [
      "bf0c0c",
      "e76a05",
      "ffc600",
      "47bc00",
      "05007b",
      "9748a8",
      "2bb3f3",
      "865200",
    ],
    brand_url: "http://www.mcdonalds.com/",
  },
  medium: {
    title: "Medium",
    colors: ["00ab6c"],
    brand_url: "https://medium.com/",
  },
  meetup: { title: "Meetup", colors: ["e0393e"], brand_url: null },
  meijer: {
    title: "Meijer",
    colors: ["0a4d8c", "dd1321"],
    brand_url: "https://www.meijer.com/",
  },
  "mercadolibre-com": {
    title: "MercadoLibre.com",
    colors: ["ffe600", "2d3277"],
    brand_url: "http://www.mercadolibre.com/",
  },
  messenger: {
    title: "Messenger",
    colors: ["0084ff"],
    brand_url: "https://www.messenger.com/",
  },
  msu: {
    title: "Michigan State University",
    colors: [
      "18453b",
      "0db14b",
      "97a2a2",
      "f08521",
      "008183",
      "909ab7",
      "535054",
      "d1de3f",
      "e8d9b5",
      "c89a58",
      "94ae4a",
      "6e005f",
      "cb5a28",
    ],
    brand_url: "https://msu.edu/",
  },
  microsoft: {
    title: "Microsoft",
    colors: ["f65314", "7cbb00", "00a1f1", "ffbb00"],
    brand_url: null,
  },
  "microsoft-band": {
    title: "Microsoft Band",
    colors: ["783bd2"],
    brand_url: "https://www.microsoft.com/microsoft-band/en-us",
  },
  "microsoft-office": {
    title: "Microsoft Office",
    colors: ["ea3e23"],
    brand_url: null,
  },
  "microsoft-surface": {
    title: "Microsoft Surface",
    colors: ["0078d7", "eeeeee", "737373", "505050", "000000"],
    brand_url: "https://www.microsoft.com/surface",
  },
  milligram: {
    title: "Milligram",
    colors: ["9b4dca", "f4f5f6", "606c76"],
    brand_url: "http://milligram.io/",
  },
  mixcloud: {
    title: "Mixcloud",
    colors: ["52aad8", "273a4b", "1d2d3b"],
    brand_url: "https://www.mixcloud.com/",
  },
  mixpanel: { title: "Mixpanel", colors: ["a086d3"], brand_url: null },
  mlb: {
    title: "MLB",
    colors: ["000088", "cc0000"],
    brand_url: "https://www.mlb.com/",
  },
  mobilink: {
    title: "Mobilink",
    colors: ["ee1d23"],
    brand_url: "http://www.mobilink.com.pk/",
  },
  mojang: {
    title: "Mojang",
    colors: ["db1f29", "000000"],
    brand_url: "https://mojang.com/",
  },
  mollie: {
    title: "Mollie",
    colors: ["c6d6df", "ec4534"],
    brand_url: "https://www.mollie.com/",
  },
  mongodb: {
    title: "MongoDB",
    colors: ["589636"],
    brand_url: "https://www.mongodb.com/",
  },
  "montclair-state-university": {
    title: "Montclair State University",
    colors: ["ce1141", "eeb111", "e87d1e", "94ce08", "00386b", "969491"],
    brand_url: "http://www.montclair.edu/",
  },
  more4: {
    title: "More4",
    colors: [
      "949483",
      "f47b7b",
      "9f1f5c",
      "ef9020",
      "00af3e",
      "85b7e2",
      "29245c",
      "ffd616",
      "e5352b",
      "e990ab",
      "0081b4",
      "96cbb3",
      "91be3e",
      "39a6dd",
      "eb0973",
      "dde2e0",
      "333c41",
    ],
    brand_url: "http://www.channel4.com/programmes/catchup/m4",
  },
  motorola: { title: "Motorola", colors: ["5c92fa"], brand_url: null },
  mozilla: {
    title: "Mozilla",
    colors: ["c13832", "d7d3c8", "4d4e53"],
    brand_url: "https://www.mozilla.org/",
  },
  musixmatch: {
    title: "Musixmatch",
    colors: [
      "ff6050",
      "ff0e83",
      "d54262",
      "813867",
      "66336e",
      "341539",
      "5677fc",
      "9013fe",
      "ffc208",
      "00cc99",
    ],
    brand_url: "https://www.musixmatch.com/",
  },
  muut: {
    title: "Muut",
    colors: ["1fadc5", "ff8000"],
    brand_url: "https://muut.com/",
  },
  myanimelist: {
    title: "MyAnimeList",
    colors: ["2e51a2"],
    brand_url: "https://myanimelist.net/",
  },
  myspace: {
    title: "MySpace",
    colors: ["000000"],
    brand_url: "https://myspace.com/",
  },
  mysql: {
    title: "MySQL",
    colors: ["00758f", "f29111"],
    brand_url: "http://www.mysql.com/",
  },
  nanowrimo: {
    title: "NaNoWriMo",
    colors: ["93dee8", "5a2e14"],
    brand_url: "https://nanowrimo.org/",
  },
  nasa: {
    title: "NASA",
    colors: ["fc3d21", "0b3d91"],
    brand_url: "https://www.nasa.gov/",
  },
  nascar: {
    title: "NASCAR",
    colors: ["ffd659", "e4002b", "007ac2"],
    brand_url: "https://www.nascar.com/",
  },
  "national-geographic": {
    title: "National Geographic",
    colors: ["ffcc00", "000000"],
    brand_url: "http://www.nationalgeographic.com/",
  },
  nationwide: {
    title: "Nationwide",
    colors: ["0071bf", "000000"],
    brand_url: "http://www.nationwide.com/",
  },
  nbc: {
    title: "NBC",
    colors: [
      "e1ac26",
      "dc380f",
      "9f0812",
      "6347b2",
      "368dd5",
      "70af1e",
      "7e887a",
    ],
    brand_url: "http://www.nbc.com",
  },
  "nc-state-university": {
    title: "NC State University",
    colors: ["cc0000", "000000"],
    brand_url: "https://www.ncsu.edu/",
  },
  nest: {
    title: "Nest",
    colors: ["00afd8", "7b858e"],
    brand_url: "https://nest.com/",
  },
  netflix: {
    title: "Netflix",
    colors: ["e50914", "221f1f", "f5f5f1"],
    brand_url: "https://www.netflix.com/",
  },
  netvibes: {
    title: "Netvibes",
    colors: ["39bd00"],
    brand_url: "http://www.netvibes.com/",
  },
  "new-balance": {
    title: "New Balance",
    colors: [
      "ce2724",
      "f3ec19",
      "207c88",
      "aac1bf",
      "e8e9d7",
      "4c4d4f",
      "231f20",
    ],
    brand_url: "http://www.newbalance.com/",
  },
  "new-york-post": {
    title: "New York Post",
    colors: ["cc3333", "2a2a2a"],
    brand_url: "http://nypost.com/",
  },
  nexar: {
    title: "Nexar",
    colors: ["fbb040", "44355b", "31263e", "ee5622", "221e22"],
    brand_url: "https://www.getnexar.com/",
  },
  nexmo: {
    title: "Nexmo",
    colors: ["0077c8", "ff8200", "f0537a"],
    brand_url: "https://www.nexmo.com/",
  },
  nextdoor: {
    title: "Nextdoor",
    colors: ["19975d"],
    brand_url: "https://nextdoor.com/newsroom/",
  },
  nfl: {
    title: "NFL",
    colors: ["013369", "d50a0a"],
    brand_url: "https://www.nfl.com/",
  },
  nhs: {
    title: "NHS",
    colors: ["005eb8", "ffffff"],
    brand_url: "https://www.nhs.uk/",
  },
  "nike-football": {
    title: "Nike Football",
    colors: ["504847", "27a770"],
    brand_url: "http://www.nike.com/us/en_us/c/football",
  },
  nikefuel: {
    title: "NikeFuel",
    colors: ["4bad31", "f5dc00", "e95814", "e2142d"],
    brand_url: "http://www.nike.com/us/en_us/c/nikeplus/nikefuel",
  },
  ning: {
    title: "Ning",
    colors: ["75af42"],
    brand_url: "http://www.ning.com/",
  },
  "ninjas-in-pyjamas": {
    title: "Ninjas in Pyjamas",
    colors: ["a98c66", "12191c", "6f7f8d", "000000"],
    brand_url: "https://nip.gl/",
  },
  nintendo: {
    title: "Nintendo",
    colors: ["e60012", "8c8c8c", "ffffff"],
    brand_url: "https://nintendo.com/",
  },
  "node-js": {
    title: "Node.js",
    colors: ["215732", "6cc24a", "44883e", "333333"],
    brand_url: "https://nodejs.org/",
  },
  nokia: { title: "Nokia", colors: ["124191"], brand_url: null },
  "norsan-media": {
    title: "Norsan Media",
    colors: ["0390d8"],
    brand_url: "http://norsanmedia.com/",
  },
  "northern-arizona-university": {
    title: "Northern Arizona University",
    colors: ["003466", "557665"],
    brand_url: "https://nau.edu/",
  },
  "northwestern-university": {
    title: "Northwestern University",
    colors: [
      "4e2a84",
      "836eaa",
      "401f68",
      "b6acd1",
      "e4e0ee",
      "342f2e",
      "716c6b",
      "bbb8b8",
      "d8d6d6",
    ],
    brand_url: "http://www.northwestern.edu",
  },
  novartis: {
    title: "Novartis",
    colors: ["765438", "a13323", "e65124", "ec7f22", "f8b22a", "ffd430"],
    brand_url: "http://www.novartis.com/",
  },
  npm: {
    title: "npm",
    colors: ["cb3837"],
    brand_url: "https://www.npmjs.com/",
  },
  ns: {
    title: "NS",
    colors: ["ffc61e", "00337f"],
    brand_url: "http://www.ns.nl/",
  },
  "ns-2": {
    title: "NS",
    colors: ["003082", "ffc917"],
    brand_url: "https://www.ns.nl/",
  },
  nvidia: { title: "NVIDIA", colors: ["76b900"], brand_url: null },
  nzxt: {
    title: "NZXT",
    colors: ["51007a", "dbe800", "d0d3d4", "7c878e"],
    brand_url: "https://www.nzxt.com/",
  },
  obb: {
    title: "ÖBB",
    colors: ["e2002a", "6e6e6e"],
    brand_url: "http://www.oebb.at/",
  },
  odnoklassniki: {
    title: "Odnoklassniki",
    colors: ["ed812b"],
    brand_url: null,
  },
  "office-sway": {
    title: "Office Sway",
    colors: ["008272"],
    brand_url: "https://sway.com/",
  },
  oktopost: {
    title: "Oktopost",
    colors: ["001f2d", "008fd4", "696969", "cccccc", "eeeeee"],
    brand_url: "https://www.oktopost.com/",
  },
  olark: {
    title: "Olark",
    colors: [
      "8d989a",
      "744da8",
      "1fb3e0",
      "49c219",
      "f4dc2a",
      "eeb417",
      "d65129",
    ],
    brand_url: "https://www.olark.com/",
  },
  olympus: {
    title: "Olympus",
    colors: ["08107b", "dfb226", "777777"],
    brand_url: "http://www.olympus.com/",
  },
  oneplus: {
    title: "OnePlus",
    colors: ["eb0029"],
    brand_url: "https://oneplus.net/",
  },
  onshape: {
    title: "Onshape",
    colors: ["1b5faa", "90cef1", "ffc20e"],
    brand_url: "https://www.onshape.com/",
  },
  oovoo: {
    title: "ooVoo",
    colors: ["eeaf00"],
    brand_url: "http://www.oovoo.com/",
  },
  opera: { title: "Opera", colors: ["cc0f16", "9c9e9f"], brand_url: null },
  oracle: {
    title: "Oracle",
    colors: ["ff0000", "000000", "7f7f7f"],
    brand_url: "http://www.oracle.com/",
  },
  "oregon-state-university": {
    title: "Oregon State University",
    colors: ["dc4405", "000000"],
    brand_url: "http://oregonstate.edu/",
  },
  overstock: {
    title: "Overstock",
    colors: ["c7202c"],
    brand_url: "https://www.overstock.com/",
  },
  "oxford-university-press": {
    title: "Oxford University Press",
    colors: ["002147", "000000", "666666"],
    brand_url: "http://global.oup.com",
  },
  "pac-12": {
    title: "Pac-12",
    colors: [
      "004b91",
      "00274d",
      "0076c0",
      "000007",
      "d6e03d",
      "a1a1a4",
      "e5c5bb",
    ],
    brand_url: "http://pac-12.com/",
  },
  panasonic: {
    title: "Panasonic",
    colors: ["0f58a8", "000000"],
    brand_url: "http://panasonic.com/",
  },
  pandora: { title: "Pandora", colors: ["005483"], brand_url: null },
  path: { title: "Path", colors: ["ee3423"], brand_url: null },
  patreon: {
    title: "Patreon",
    colors: ["f96854", "052d49"],
    brand_url: "https://www.patreon.com/",
  },
  paymill: {
    title: "PAYMILL",
    colors: ["f05000"],
    brand_url: "https://www.paymill.com/",
  },
  paymo: {
    title: "Paymo",
    colors: ["22d0b8", "34c950", "8de86e"],
    brand_url: "https://www.paymoapp.com/",
  },
  paypal: {
    title: "PayPal",
    colors: ["003087", "009cde", "012169"],
    brand_url: "https://www.paypal.com/",
  },
  pearson: {
    title: "Pearson",
    colors: ["ed6b06", "9d1348", "008b5d", "364395"],
    brand_url: "https://www.pearson.com",
  },
  "penguin-books": {
    title: "Penguin Books",
    colors: ["ff6900"],
    brand_url: "http://www.penguin.com/",
  },
  "peopleperhour-com": {
    title: "PeoplePerHour.com",
    colors: ["ee7200"],
    brand_url: "https://www.peopleperhour.com/",
  },
  pepsi: {
    title: "Pepsi",
    colors: ["e32934", "004883"],
    brand_url: "http://www.pepsi.com/",
  },
  periscope: {
    title: "Periscope",
    colors: ["3aa4c6", "d75444"],
    brand_url: "https://www.periscope.tv/",
  },
  pfizer: {
    title: "Pfizer",
    colors: [
      "0093d0",
      "000000",
      "616365",
      "00aeef",
      "d6006e",
      "75d1e0",
      "7dba00",
      "cc292b",
      "00a950",
      "f8971d",
      "f7d417",
      "4a245e",
      "f26649",
    ],
    brand_url: "http://www.pfizer.com/",
  },
  philips: {
    title: "Philips",
    colors: ["0e5fd8"],
    brand_url: "http://www.philips.com/",
  },
  photobucket: {
    title: "Photobucket",
    colors: ["0ea0db", "000000"],
    brand_url: "http://photobucket.com/",
  },
  php: {
    title: "PHP",
    colors: ["8892be", "4f5b93", "99cc99"],
    brand_url: "http://php.net/",
  },
  pikabu: {
    title: "Pikabu",
    colors: ["5dbe57"],
    brand_url: "https://pikabu.ru/",
  },
  pinboard: { title: "Pinboard", colors: ["0000e6"], brand_url: null },
  pinterest: {
    title: "Pinterest",
    colors: ["e60023"],
    brand_url: "https://www.pinterest.com/",
  },
  "pizza-hut": {
    title: "Pizza Hut",
    colors: ["ee3124", "00a160", "ffc425"],
    brand_url: "http://www.pizzahut.com",
  },
  plasso: {
    title: "Plasso",
    colors: ["6585ed", "f5756c", "98afc0", "2f3148"],
    brand_url: null,
  },
  plaxo: {
    title: "Plaxo",
    colors: ["414f5a"],
    brand_url: "http://www.plaxo.com/",
  },
  playstation: { title: "PlayStation", colors: ["003087"], brand_url: null },
  plex: {
    title: "Plex",
    colors: ["e5a00d", "282a2d"],
    brand_url: "https://www.plex.tv/",
  },
  pocket: {
    title: "Pocket",
    colors: ["ef4056", "50bcb6"],
    brand_url: "https://getpocket.com/",
  },
  "poczta-polska": {
    title: "Poczta Polska",
    colors: ["d52b1e"],
    brand_url: "http://www.poczta-polska.pl/",
  },
  polariod: {
    title: "Polariod",
    colors: ["00a3e2", "1ba548", "fdc800", "f1860e", "e41b13"],
    brand_url: "http://www.polaroid.com/",
  },
  portfolium: {
    title: "Portfolium",
    colors: ["0099ff", "fb0a2a", "17ad49", "333333"],
    brand_url: "https://portfolium.com/",
  },
  postman: {
    title: "Postman",
    colors: ["ef5b25"],
    brand_url: "https://www.getpostman.com/",
  },
  postmates: {
    title: "Postmates",
    colors: ["000000", "36454f"],
    brand_url: "https://postmates.com/",
  },
  prestashop: {
    title: "PrestaShop",
    colors: ["df0067", "251b5b", "25b9d7", "fbbb22", "68737f", "bbbfc3"],
    brand_url: "https://www.prestashop.com/",
  },
  prezi: { title: "Prezi", colors: ["318bff"], brand_url: null },
  priceline: {
    title: "Priceline",
    colors: ["1885bf"],
    brand_url: "http://www.priceline.com/",
  },
  "princeton-university": {
    title: "Princeton University",
    colors: ["ee7f2d", "000000"],
    brand_url: "https://www.princeton.edu/",
  },
  "product-hunt": {
    title: "Product Hunt",
    colors: ["da552f", "534540", "988f8c", "00b27f"],
    brand_url: "http://www.producthunt.com/",
  },
  protonmail: {
    title: "ProtonMail",
    colors: ["505264", "8a90c7"],
    brand_url: "https://protonmail.com/",
  },
  puma: {
    title: "Puma",
    colors: ["000000", "44403f", "696965", "ba2026", "ae946d"],
    brand_url: "http://puma.com/",
  },
  "purdue-university": {
    title: "Purdue University",
    colors: ["c28e0e", "98700d", "000000"],
    brand_url: "https://www.purdue.edu/",
  },
  python: {
    title: "Python",
    colors: ["ffde57", "4584b6", "646464"],
    brand_url: "https://www.python.org/",
  },
  "qantas-airlines": {
    title: "Qantas Airways",
    colors: ["e0001b"],
    brand_url: "http://www.qantas.com.au/",
  },
  qualtrics: {
    title: "Qualtrics",
    colors: ["e10019"],
    brand_url: "https://www.qualtrics.com",
  },
  quizlet: {
    title: "Quizlet",
    colors: ["4257b2", "3ccfcf", "f0f0f0"],
    brand_url: "https://quizlet.com",
  },
  quizup: {
    title: "QuizUp",
    colors: ["ff5454"],
    brand_url: "https://www.quizup.com/",
  },
  quora: { title: "Quora", colors: ["a82400"], brand_url: null },
  "quote-fm": { title: "QUOTE.fm", colors: ["66ceff"], brand_url: null },
  "raspberry-pi": {
    title: "Raspberry Pi",
    colors: ["c7053d", "8cc04b"],
    brand_url: "https://www.raspberrypi.org/",
  },
  razer: {
    title: "Razer",
    colors: ["00ff00"],
    brand_url: "http://www.razerzone.com/",
  },
  rdio: { title: "Rdio", colors: ["007dc3"], brand_url: null },
  remax: {
    title: "RE/MAX",
    colors: ["e11b22", "0054a4"],
    brand_url: "http://www.remax.com/",
  },
  react: {
    title: "React",
    colors: ["00d8ff"],
    brand_url: "https://facebook.github.io/react/",
  },
  readability: { title: "Readability", colors: ["990000"], brand_url: null },
  "realex-payments": {
    title: "Realex Payments",
    colors: ["f29023", "4d5255"],
    brand_url: "https://www.realexpayments.com/",
  },
  "red-hat": { title: "Red Hat", colors: ["cc0000"], brand_url: null },
  reddit: {
    title: "Reddit",
    colors: ["ff4500", "5f99cf", "cee3f8"],
    brand_url: null,
  },
  redfin: {
    title: "Redfin",
    colors: ["a02021"],
    brand_url: "https://www.redfin.com",
  },
  redox: {
    title: "Redox",
    colors: ["0a2239", "01b287", "ff9f1c", "e5505a", "854c9e"],
    brand_url: "https://www.redoxengine.com/",
  },
  "renaissance-hotels": {
    title: "Renaissance Hotels",
    colors: ["000000", "999999", "f58021"],
    brand_url: "http://renaissance-hotels.marriott.com/",
  },
  rentler: {
    title: "Rentler",
    colors: ["ed1c27"],
    brand_url: "https://www.rentler.com/",
  },
  "residence-inn": {
    title: "Residence Inn",
    colors: ["b32317", "f58025", "3a6e8f", "87b2d8", "8d8b00", "c1d72f"],
    brand_url: "http://www.residenceinn.marriott.com/",
  },
  reverbnation: { title: "ReverbNation", colors: ["e43526"], brand_url: null },
  "rochester-institute-of-technology": {
    title: "Rochester Institute of Technology",
    colors: ["f36e21", "513127"],
    brand_url: "https://www.rit.edu/",
  },
  rit: {
    title: "Rochester Institute of Technology",
    colors: ["f76902", "ffffff", "000000"],
    brand_url: "https://www.rit.edu/",
  },
  rockpack: { title: "Rockpack", colors: ["0ba6ab"], brand_url: null },
  roku: {
    title: "Roku",
    colors: ["6f1ab1"],
    brand_url: "https://www.roku.com/",
  },
  "rolls-royce": {
    title: "Rolls-Royce",
    colors: ["680021", "fffaec", "939598", "000000"],
    brand_url: "http://www.rolls-roycemotorcars.com/",
  },
  "roo-kids": {
    title: "Roo Kids",
    colors: ["e22027", "a1cd3d", "003e70"],
    brand_url: "http://www.rookidsapp.com/",
  },
  roon: { title: "Roon", colors: ["62b0d9"], brand_url: null },
  "rosetta-stone": {
    title: "Rosetta Stone",
    colors: ["0098db", "ecc400"],
    brand_url: "http://www.rosettastone.com/",
  },
  rounds: {
    title: "Rounds",
    colors: ["fdd800"],
    brand_url: "https://www.rounds.com/",
  },
  "rowan-university": {
    title: "Rowan University",
    colors: ["3f1a0a", "edd51c"],
    brand_url: "http://www.rowan.edu/home/",
  },
  cssd: {
    title: "Royal Central School of Speech and Drama",
    colors: [
      "1b5692",
      "c32128",
      "43a756",
      "999999",
      "de8a3d",
      "74a2d7",
      "f0c33b",
      "9fc54d",
    ],
    brand_url: "https://www.cssd.ac.uk",
  },
  "royal-mail": {
    title: "Royal Mail",
    colors: ["ff0000", "ffff00", "000000"],
    brand_url: "http://www.royalmail.com/",
  },
  "rss-2": { title: "RSS", colors: ["f26522"], brand_url: null },
  ruby: {
    title: "Ruby",
    colors: ["cc342d"],
    brand_url: "https://www.ruby-lang.org/",
  },
  "ruby-on-rails": {
    title: "Ruby on Rails",
    colors: ["cc0000"],
    brand_url: "http://rubyonrails.org/",
  },
  "rutgers-university": {
    title: "Rutgers University",
    colors: ["cc0033"],
    brand_url: "http://www.rutgers.edu/",
  },
  ryanair: {
    title: "Ryanair",
    colors: ["073590", "f1c933", "2091eb"],
    brand_url: "https://www.ryanair.com/us/en/",
  },
  sabre: {
    title: "Sabre",
    colors: ["e50000", "111111"],
    brand_url: "https://www.sabre.com/",
  },
  sage: {
    title: "Sage",
    colors: ["00dc06"],
    brand_url: "https://www.sage.com/",
  },
  sainsburys: {
    title: "Sainsbury's",
    colors: ["ec8a00"],
    brand_url: "http://www.j-sainsbury.co.uk/",
  },
  salesforce: {
    title: "Salesforce",
    colors: ["1798c1", "ff1100"],
    brand_url: null,
  },
  samsung: {
    title: "Samsung",
    colors: [
      "1428a0",
      "75787b",
      "0689d8",
      "ffc600",
      "ff6900",
      "e4002b",
      "c800a1",
      "685bc7",
      "0057b8",
      "00a9e0",
      "009ca6",
      "00b140",
    ],
    brand_url: null,
  },
  "san-francisco-49ers": {
    title: "San Francisco 49ers",
    colors: ["e91e22", "c8aa76", "000000"],
    brand_url: "http://www.49ers.com/",
  },
  "san-francisco-giants": {
    title: "San Francisco Giants",
    colors: ["fd5a1e", "000000"],
    brand_url: "http://sanfrancisco.giants.mlb.com/",
  },
  sap: {
    title: "SAP",
    colors: ["003366", "999999"],
    brand_url: "http://go.sap.com/",
  },
  "scouts-uk": {
    title: "Scouts UK",
    colors: [
      "4d2177",
      "84a40b",
      "004851",
      "009a44",
      "0095c8",
      "003da5",
      "002855",
      "004851",
      "ffcd00",
      "ff8200",
      "ba0c2f",
      "ad1aac",
      "7c3a2d",
      "8c857b",
    ],
    brand_url: "http://scouts.org.uk/",
  },
  scribd: {
    title: "Scribd",
    colors: ["1a7bba"],
    brand_url: "https://www.scribd.com/",
  },
  septa: {
    title: "SEPTA",
    colors: ["1f4fa3", "f14728"],
    brand_url: "http://www.septa.org/",
  },
  "seton-hall-university": {
    title: "Seton Hall University",
    colors: ["004488"],
    brand_url: "https://www.shu.edu/",
  },
  shazam: {
    title: "Shazam",
    colors: [
      "0088ff",
      "ffaa00",
      "ff7700",
      "ff0033",
      "9911aa",
      "cc2288",
      "aadd22",
      "242424",
      "646464",
      "949494",
      "e4e4e4",
      "f4f4f4",
    ],
    brand_url: "http://www.shazam.com/",
  },
  "sherwin-williams": {
    title: "Sherwin-Williams",
    colors: ["0168b3", "ee3e34"],
    brand_url: "http://www.sherwin-williams.com/",
  },
  shopify: {
    title: "Shopify",
    colors: ["96bf48", "479ccf", "2d3538", "f5f5f5", "f2f7fa", "666666"],
    brand_url: null,
  },
  shopmium: {
    title: "Shopmium",
    colors: ["f01f74"],
    brand_url: "https://www.shopmium.com/",
  },
  siemens: {
    title: "Siemens",
    colors: ["009999"],
    brand_url: "http://www.siemens.com/",
  },
  skillshare: {
    title: "Skillshare",
    colors: ["f26b21", "68b8be"],
    brand_url: "https://www.skillshare.com/",
  },
  skoda: {
    title: "Skoda",
    colors: ["00800d"],
    brand_url: "http://www.skoda-auto.com/",
  },
  skype: { title: "Skype", colors: ["00aff0"], brand_url: null },
  skywest: {
    title: "SkyWest",
    colors: ["00338d"],
    brand_url: "http://www.skywest.com/",
  },
  slack: {
    title: "Slack",
    colors: ["6ecadc", "e9a820", "e01563", "3eb991"],
    brand_url: "https://slack.com/",
  },
  slideshare: {
    title: "SlideShare",
    colors: ["0077b5"],
    brand_url: "http://www.slideshare.net/",
  },
  slipcase: {
    title: "Slipcase",
    colors: ["7c9cb0"],
    brand_url: "https://www.slipcase.com/",
  },
  "smashing-magazine": {
    title: "Smashing Magazine",
    colors: ["e53b2c", "41b7d8"],
    brand_url: null,
  },
  snagajob: {
    title: "Snagajob",
    colors: ["f36f21"],
    brand_url: "http://www.snagajob.com/",
  },
  snapchat: {
    title: "Snapchat",
    colors: ["fffc00"],
    brand_url: "https://www.snapchat.com/",
  },
  soapui: {
    title: "SoapUI",
    colors: ["6cb33f", "4a494d"],
    brand_url: "https://www.soapui.org/",
  },
  socialbro: {
    title: "SocialBro",
    colors: ["29c4d0", "f29556", "84afa2", "72c427", "f24c7c", "00aaf2"],
    brand_url: "http://www.socialbro.com/",
  },
  softonic: { title: "Softonic", colors: ["008ace"], brand_url: null },
  songkick: {
    title: "Songkick",
    colors: ["f80046"],
    brand_url: "http://www.songkick.com/",
  },
  sonicbids: {
    title: "Sonicbids",
    colors: ["ff6600", "0c88b1"],
    brand_url: "http://www.sonicbids.com/",
  },
  sonos: {
    title: "Sonos",
    colors: ["d8a158", "ba4724", "1c5f4a", "d8d8d8"],
    brand_url: "https://sonos.com",
  },
  sony: {
    title: "Sony",
    colors: [
      "000000",
      "7c8285",
      "bfbdb0",
      "b1b134",
      "bbd634",
      "dbe3b6",
      "b2c8bd",
      "165b65",
      "697d99",
      "96b8db",
      "00a4e8",
      "a4dbdb",
      "fdd666",
      "dc9018",
      "e31a22",
      "df8f2d",
      "b24f3f",
      "b51f29",
      "f58268",
      "f4979c",
    ],
    brand_url: "https://www.sony.com/",
  },
  soulcycle: {
    title: "Soulcycle",
    colors: ["fedf00", "1e1e1e", "a7a8aa"],
    brand_url: "https://www.soul-cycle.com/",
  },
  soundcloud: {
    title: "SoundCloud",
    colors: ["ff8800", "ff3300"],
    brand_url: null,
  },
  spoken: {
    title: "Spoken",
    colors: ["fc00c1", "000000"],
    brand_url: "https://spoken.co/",
  },
  spotify: {
    title: "Spotify",
    colors: ["1db954", "191414"],
    brand_url: "https://www.spotify.com/",
  },
  sprint: { title: "Sprint", colors: ["ffe100"], brand_url: null },
  "sprout-social": {
    title: "Sprout Social",
    colors: ["75dd66", "59cb59", "2bb656", "0ca750", "f3f4f4", "364141"],
    brand_url: "http://sproutsocial.com/",
  },
  "square-cash": {
    title: "Square Cash",
    colors: ["28c101"],
    brand_url: "https://cash.me/",
  },
  squarespace: { title: "Squarespace", colors: ["222222"], brand_url: null },
  "stack-exchange": {
    title: "Stack Exchange",
    colors: ["1e5397", "376db6", "4ca2da", "91d8f4"],
    brand_url: "http://stackexchange.com/",
  },
  stackoverflow: {
    title: "Stack Overflow",
    colors: ["f48024", "222426", "bcbbbb"],
    brand_url: "http://stackoverflow.com/",
  },
  staples: {
    title: "Staples",
    colors: ["cc0000", "2c8aec", "ffcc00"],
    brand_url: null,
  },
  starbucks: {
    title: "Starbucks",
    colors: ["00704a"],
    brand_url: "http://www.starbucks.com/",
  },
  "state-farm": {
    title: "State Farm",
    colors: ["e1261c"],
    brand_url: "https://www.statefarm.com/",
  },
  "status-chart": {
    title: "Status Chart",
    colors: ["d7584f"],
    brand_url: null,
  },
  steam: {
    title: "Steam",
    colors: ["00adee", "000000"],
    brand_url: "http://steampowered.com/",
  },
  "sterling-hotels": {
    title: "Sterling Hotels",
    colors: [
      "3b5a6f",
      "828a87",
      "000000",
      "9db7c4",
      "ccd7dd",
      "838f97",
      "002054",
    ],
    brand_url: "https://preferredhotelgroup.com/sterling",
  },
  "stockton-university": {
    title: "Stockton University",
    colors: ["000000", "79bde9", "ffc423", "bc9b6a", "a7a9ac"],
    brand_url: "https://www.stockton.edu/",
  },
  storyful: {
    title: "Storyful",
    colors: ["f97200", "010101", "8b8b64", "bbbdc0"],
    brand_url: "http://storyful.com/",
  },
  strava: { title: "Strava", colors: ["fc4c02"], brand_url: null },
  streamable: {
    title: "Streamable",
    colors: ["0f90fa"],
    brand_url: "http://streamable.com/",
  },
  stripe: { title: "Stripe", colors: ["00afe1"], brand_url: null },
  stubhub: {
    title: "StubHub",
    colors: ["004b91", "ff7300"],
    brand_url: "http://www.stubhub.com/",
  },
  studyblue: { title: "StudyBlue", colors: ["00afe1"], brand_url: null },
  stumbleupon: { title: "StumbleUpon", colors: ["eb4924"], brand_url: null },
  subway: {
    title: "Subway",
    colors: ["489e3b", "fabd42", "cd0a20"],
    brand_url: "http://www.subway.com/",
  },
  sugarcrm: {
    title: "SugarCRM",
    colors: ["e61718", "e8e9ea", "595a5c", "282828"],
    brand_url: "http://www.sugarcrm.com/",
  },
  suntrust: {
    title: "SunTrust",
    colors: ["00447c", "fdb913", "e36f1e"],
    brand_url: "https://www.suntrust.com/",
  },
  supershuttle: {
    title: "SuperShuttle",
    colors: ["4285f4", "ffcd1a"],
    brand_url: "https://www.supershuttle.com/",
  },
  swarm: {
    title: "Swarm",
    colors: ["f06d1f", "ffa633"],
    brand_url: "https://www.swarmapp.com/",
  },
  "t-mobile": { title: "T-Mobile", colors: ["e20074"], brand_url: null },
  tagstr: {
    title: "Tagstr",
    colors: ["e74635"],
    brand_url: "https://tagstr.co/",
  },
  taiga: {
    title: "Taiga",
    colors: ["444444", "b8b8b8", "72a114", "9dce0a", "879b89"],
    brand_url: "https://taiga.io/",
  },
  target: {
    title: "Target",
    colors: ["cc0000"],
    brand_url: "http://www.target.com/",
  },
  technorati: { title: "Technorati", colors: ["339900"], brand_url: null },
  ted: { title: "TED", colors: ["e62b1e"], brand_url: "http://www.ted.com/" },
  telegram: {
    title: "Telegram",
    colors: ["0088cc"],
    brand_url: "https://telegram.org/",
  },
  tvtag: {
    title: "Telfie",
    colors: ["e92c4c", "c82641"],
    brand_url: "http://telfie.com/",
  },
  temple: {
    title: "Temple",
    colors: ["a41e35", "222222", "899197"],
    brand_url: "https://www.temple.edu/",
  },
  tesco: {
    title: "Tesco",
    colors: ["ee1c2e", "00539f"],
    brand_url: "http://www.tesco.com/",
  },
  tesla: {
    title: "Tesla",
    colors: ["cc0000"],
    brand_url: "http://www.teslamotors.com/",
  },
  "texas-am-university": {
    title: "Texas AM University",
    colors: [
      "500000",
      "003c71",
      "5b6236",
      "744f28",
      "998542",
      "332c2c",
      "707373",
      "d6d3c4",
    ],
    brand_url: "http://www.tamu.edu/",
  },
  "texas-tech-university": {
    title: "Texas Tech University",
    colors: ["cc0000", "000000"],
    brand_url: "http://www.ttu.edu/",
  },
  "the-audience-awards": {
    title: "The Audience Awards",
    colors: ["ee8421", "8c8a8a", "222222"],
    brand_url: "http://theaudienceawards.com/",
  },
  "the-college-of-new-jersey": {
    title: "The College of New Jersey",
    colors: ["293f6f", "a67a00"],
    brand_url: "http://tcnj.pages.tcnj.edu/",
  },
  "the-next-web": {
    title: "The Next Web",
    colors: ["ff3c1f", "26313b", "4e5860", "a6abaf", "d9e0e2", "fafbfc"],
    brand_url: null,
  },
  "the-ritz-carlton": {
    title: "The Ritz-Carlton",
    colors: ["006b95", "4f5b65", "b3812a", "a01a1f"],
    brand_url: "http://www.ritzcarlton.com/",
  },
  "the-sun": {
    title: "The Sun",
    colors: ["ed1c24", "b90c13"],
    brand_url: "http://www.thesun.co.uk/",
  },
  "the-sun-goals": {
    title: "The Sun Goals",
    colors: ["00745e", "086556"],
    brand_url: "http://www.thesun.co.uk/goals/",
  },
  "the-sun-perks": {
    title: "The Sun Perks",
    colors: ["8560a8", "431c69"],
    brand_url: "http://perks.thesun.co.uk/",
  },
  "the-times": {
    title: "The Times",
    colors: ["000000"],
    brand_url: "http://www.thetimes.co.uk/",
  },
  "thomson-reuters": {
    title: "Thomson Reuters",
    colors: [
      "ff8000",
      "555555",
      "444444",
      "666666",
      "cccccc",
      "e9e9e9",
      "f7f7f7",
    ],
    brand_url: "http://thomsonreuters.com/",
  },
  tivo: {
    title: "TiVo",
    colors: [
      "da3d34",
      "00a480",
      "ed9f40",
      "6a76ac",
      "17170e",
      "534b38",
      "a6a480",
    ],
    brand_url: "http://www.tivo.com/",
  },
  totaljobs: {
    title: "Totaljobs",
    colors: ["66bd00"],
    brand_url: "https://www.totaljobs.com/",
  },
  toyota: {
    title: "Toyota",
    colors: ["eb0a1e", "ffffff", "000000", "58595b"],
    brand_url: "https://www.toyota.com/",
  },
  treehouse: {
    title: "Treehouse",
    colors: ["6fbc6d", "47535b"],
    brand_url: null,
  },
  trello: {
    title: "Trello",
    colors: [
      "0079bf",
      "70b500",
      "ff9f1a",
      "eb5a46",
      "f2d600",
      "c377e0",
      "ff78cb",
      "00c2e0",
      "51e898",
      "c4c9cc",
    ],
    brand_url: "https://trello.com/",
  },
  tripadvisor: {
    title: "TripAdvisor",
    colors: ["00af87"],
    brand_url: "http://www.tripadvisor.com/",
  },
  trulia: { title: "Trulia", colors: ["5eab1f"], brand_url: null },
  trustpilot: {
    title: "Trustpilot",
    colors: ["e12729", "f37324", "f8cc1b", "72b043", "007f4e", "c8c8c8"],
    brand_url: "https://www.trustpilot.com/",
  },
  tumblr: { title: "Tumblr", colors: ["35465c"], brand_url: null },
  tunngle: {
    title: "Tunngle",
    colors: ["c30f24"],
    brand_url: "http://www.tunngle.net/",
  },
  turbotax: {
    title: "TurboTax",
    colors: ["355ebe", "d52b1d"],
    brand_url: "https://turbotax.intuit.com/",
  },
  twentythree: {
    title: "TwentyThree",
    colors: ["1ec95b", "043623", "eff5f0"],
    brand_url: "https://www.twentythree.net/",
  },
  twitch: {
    title: "Twitch",
    colors: ["9146ff", "000000", "f0f0ff"],
    brand_url: "https://twitch.tv",
  },
  twitter: {
    title: "Twitter",
    colors: ["1da1f2", "14171a", "657786", "aab8c2", "e1e8ed", "f5f8fa"],
    brand_url: "https://twitter.com/",
  },
  typekit: { title: "Typekit", colors: ["98ce1e"], brand_url: null },
  typepad: {
    title: "Typepad",
    colors: ["d2de61"],
    brand_url: "http://www.typepad.com/",
  },
  typescript: {
    title: "TypeScript",
    colors: ["3178c6", "00273f"],
    brand_url: "https://www.typescriptlang.org/",
  },
  typo3: { title: "TYPO3", colors: ["ff8700"], brand_url: "http://typo3.org/" },
  uber: {
    title: "Uber",
    colors: ["09091a", "c0c0c8", "1fbad6"],
    brand_url: "https://www.uber.com",
  },
  ubuntu: {
    title: "Ubuntu",
    colors: ["dd4814", "77216f", "5e2750", "2c001e", "aea79f", "333333"],
    brand_url: null,
  },
  "uc-berkeley": {
    title: "UC Berkeley",
    colors: ["003262", "3b7ea1", "fdb515", "c4820e"],
    brand_url: "http://www.berkeley.edu/",
  },
  ucsf: {
    title: "UCSF",
    colors: ["052049", "18a3ac", "90bd31", "178ccb", "f48024"],
    brand_url: "http://www.ucsf.edu",
  },
  "united-way": {
    title: "United Way",
    colors: [
      "10167f",
      "fe230a",
      "ff9600",
      "000064",
      "b41428",
      "f57814",
      "e6d7aa",
      "505050",
      "f0e6c8",
      "969696",
      "7c81b8",
      "ff967d",
      "ffc87d",
    ],
    brand_url: "http://www.unitedway.org/",
  },
  unity: {
    title: "Unity",
    colors: [
      "222c37",
      "00cccc",
      "fff600",
      "ff0066",
      "19e3b1",
      "ff7f33",
      "b83c82",
    ],
    brand_url: "http://unity3d.com/",
  },
  "universitat-hamburg": {
    title: "Universität Hamburg",
    colors: ["e2001a", "009cd1", "3b515b"],
    brand_url: "https://www.uni-hamburg.de/",
  },
  "university-at-albany": {
    title: "University at Albany",
    colors: ["46166b", "eeb211", "006c68", "97a4af"],
    brand_url: "https://www.albany.edu/",
  },
  "university-at-buffalo": {
    title: "University at Buffalo",
    colors: [
      "005bbb",
      "e56a54",
      "ffc72c",
      "ebec00",
      "00a69c",
      "990000",
      "ad841f",
      "6da04b",
      "006570",
      "2f9fd0",
      "002f56",
      "e4e4e4",
      "666666",
    ],
    brand_url: "http://www.buffalo.edu/",
  },
  "university-of-alberta": {
    title: "University of Alberta",
    colors: ["007c41", "ffdb05"],
    brand_url: "https://www.ualberta.ca/",
  },
  "university-of-arizona": {
    title: "University of Arizona",
    colors: ["cc0033", "003366"],
    brand_url: "http://www.arizona.edu/",
  },
  "university-of-cambridge": {
    title: "University of Cambridge",
    colors: ["d6083b", "0072cf", "ea7125", "55a51c", "8f2bbc", "00b1c1"],
    brand_url: "https://www.cam.ac.uk/",
  },
  "university-of-cincinnati": {
    title: "University of Cincinnati",
    colors: ["e00122", "000000"],
    brand_url: "https://www.uc.edu/",
  },
  "university-of-dayton": {
    title: "University of Dayton",
    colors: [
      "ce1141",
      "004b8d",
      "000000",
      "faf2f3",
      "d1cdb8",
      "cf0a2c",
      "0082ca",
      "199051",
      "e76829",
      "ffdd00",
    ],
    brand_url: "https://udayton.edu/",
  },
  "university-of-florida": {
    title: "University of Florida",
    colors: ["fa4616", "0021a5"],
    brand_url: "http://www.ufl.edu/",
  },
  "university-of-illinois-urbana-champaign": {
    title: "University of Illinois Urbana-Champaign",
    colors: ["131f33", "fa6300"],
    brand_url: "http://illinois.edu/",
  },
  "university-of-kentucky": {
    title: "University of Kentucky",
    colors: ["005daa"],
    brand_url: "http://www.uky.edu/",
  },
  "university-of-michigan": {
    title: "University of Michigan",
    colors: ["00274c", "ffcb05"],
    brand_url: "http://umich.edu/",
  },
  "university-of-north-carolina": {
    title: "University of North Carolina",
    colors: ["4b9cd3", "007fae", "13294b", "e1e1e1", "767676", "151515"],
    brand_url: "https://www.unc.edu/",
  },
  "university-of-oregon": {
    title: "University of Oregon",
    colors: ["154733", "fee123"],
    brand_url: "https://uoregon.edu/",
  },
  "university-of-rochester": {
    title: "University of Rochester",
    colors: ["ffd100", "003b71"],
    brand_url: "https://www.rochester.edu/",
  },
  "university-of-texas": {
    title: "University of Texas",
    colors: [
      "bf5700",
      "333f48",
      "005f86",
      "43695b",
      "f2a900",
      "382f2d",
      "d6d2c4",
    ],
    brand_url: "https://www.utexas.edu/",
  },
  "university-of-victoria": {
    title: "University of Victoria",
    colors: ["005493", "f5aa1c", "c63527", "002754"],
    brand_url: "http://www.uvic.ca/",
  },
  "university-of-washington": {
    title: "University of Washington",
    colors: ["4b2e83", "b7a57a", "85754d"],
    brand_url: "http://www.washington.edu/",
  },
  "university-of-waterloo": {
    title: "University of Waterloo",
    colors: ["ffd54f", "000"],
    brand_url: "https://uwaterloo.ca/",
  },
  "university-of-wisconsin-milwaukee": {
    title: "University of Wisconsin-Milwaukee",
    colors: [
      "ffbd00",
      "000000",
      "98c646",
      "694d88",
      "5382af",
      "d06d34",
      "5f9a38",
      "474d52",
    ],
    brand_url: "http://uwm.edu/",
  },
  univision: { title: "Univision", colors: ["c822b0"], brand_url: null },
  ups: {
    title: "UPS",
    colors: ["351c15", "ffb500", "64a70b"],
    brand_url: "https://www.ups.com/",
  },
  usps: {
    title: "USPS",
    colors: ["333366", "e71921", "218748"],
    brand_url: "https://www.usps.com/",
  },
  ustream: { title: "Ustream", colors: ["3388ff"], brand_url: null },
  verizon: {
    title: "Verizon",
    colors: ["ff0000", "f2f2f2", "3285dc"],
    brand_url: null,
  },
  viadeo: {
    title: "Viadeo",
    colors: ["f07355"],
    brand_url: "http://viadeo.com/",
  },
  viber: {
    title: "Viber",
    colors: ["59267c", "8f5db7", "e2d4e7", "a5cfd5", "81cd50"],
    brand_url: "http://www.viber.com/",
  },
  vidme: {
    title: "Vidme",
    colors: ["f82a53", "111111", "f5f5f5", "9f2af8", "aaaaaa", "dff0d8"],
    brand_url: "https://vid.me/",
  },
  viki: {
    title: "Viki",
    colors: ["3c9cd7", "d24663"],
    brand_url: "http://www.viki.com/",
  },
  vimeo: { title: "Vimeo", colors: ["162221", "1ab7ea"], brand_url: null },
  vine: { title: "Vine", colors: ["00b488"], brand_url: null },
  virb: { title: "Virb", colors: ["1e91d0"], brand_url: null },
  "virgin-media": {
    title: "Virgin Media",
    colors: ["c3092d", "222221"],
    brand_url: null,
  },
  "virgin-money": {
    title: "Virgin Money",
    colors: ["cc0000", "333333", "a93c3b", "a896a0", "7a3671", "bd1d65"],
    brand_url: "https://virginmoney.com/",
  },
  visa: {
    title: "Visa",
    colors: ["1a1f71", "f7b600"],
    brand_url: "https://www.visa.com/",
  },
  visualcv: {
    title: "VisualCV",
    colors: ["31577a"],
    brand_url: "https://www.visualcv.com/",
  },
  visually: {
    title: "Visually",
    colors: ["14acf2", "f04494", "0ac578"],
    brand_url: "http://visual.ly/",
  },
  vkontakte: { title: "VKontakte", colors: ["45668e"], brand_url: null },
  vodafone: {
    title: "Vodafone",
    colors: [
      "e60000",
      "4a4d4e",
      "9c2aa0",
      "5e2750",
      "00b0ca",
      "007c92",
      "a8b400",
      "fecb00",
      "eb9800",
      "000000",
    ],
    brand_url: "http://www.vodafone.com/content/index.html",
  },
  volvo: {
    title: "Volvo",
    colors: ["003057", "115740", "65665c", "425563", "517891", "212721"],
    brand_url: "http://www.volvocars.com",
  },
  "vue-js": {
    title: "Vue.js",
    colors: ["42b883", "35495e"],
    brand_url: "https://vuejs.org/",
  },
  "wake-forest-university": {
    title: "Wake Forest University",
    colors: [
      "9e7e38",
      "000000",
      "82231c",
      "511536",
      "443e67",
      "375669",
      "456525",
      "59786c",
      "3d3c1d",
      "625750",
    ],
    brand_url: "http://www.wfu.edu/",
  },
  walgreens: {
    title: "Walgreens",
    colors: ["e31837", "f37520", "489cd4", "2774a6", "35393d"],
    brand_url: "http://www.walgreens.com/",
  },
  walmart: {
    title: "Walmart",
    colors: [
      "007dc6",
      "79b9e7",
      "f47421",
      "76c143",
      "ffc120",
      "e7f0f7",
      "f2f8fd",
      "222222",
      "444444",
    ],
    brand_url: "http://www.walmart.com/",
  },
  "warby-parker": {
    title: "Warby Parker",
    colors: ["414b56", "00a2e1"],
    brand_url: "https://www.warbyparker.com/",
  },
  "wave-apps": {
    title: "Wave Apps",
    colors: ["1c2d37", "4ec7c4", "00959f", "3b9bcc"],
    brand_url: "https://www.waveapps.com/",
  },
  webzunder: {
    title: "webZunder",
    colors: ["eea642"],
    brand_url: "https://www.webzunder.com/",
  },
  wechat: {
    title: "WeChat",
    colors: ["7bb32e"],
    brand_url: "http://www.wechat.com/",
  },
  wendys: {
    title: "Wendy's",
    colors: ["e2203d", "199fda"],
    brand_url: "https://www.wendys.com/",
  },
  "western-digital": {
    title: "Western Digital",
    colors: ["005195", "028948", "ffd400", "0067b3", "9d0a0e", "003369"],
    brand_url: "http://www.wdc.com/",
  },
  whatsapp: {
    title: "WhatsApp",
    colors: ["075e54", "128c7e", "25d366", "dcf8c6", "34b7f1", "ece5dd"],
    brand_url: "https://www.whatsapp.com/",
  },
  whatsbroadcast: {
    title: "WhatsBroadcast",
    colors: [
      "4aae20",
      "6cc751",
      "225f1e",
      "f8cc07",
      "ff9300",
      "e44436",
      "cd3292",
      "37aef3",
      "0076ba",
      "005888",
      "8732cd",
      "33482c",
    ],
    brand_url: "https://www.whatsbroadcast.com/",
  },
  "whoosnap-designer": {
    title: "Whoosnap",
    colors: ["2fa5d6", "b52f2c"],
    brand_url: "http://whoosnap.com/",
  },
  wikimedia: {
    title: "Wikimedia",
    colors: ["339966", "0063bf", "990000"],
    brand_url: "https://www.wikimedia.org/",
  },
  wikipedia: {
    title: "Wikipedia",
    colors: ["000000", "636466", "939598", "c7c8ca"],
    brand_url: "https://www.wikipedia.org/",
  },
  windows: {
    title: "Windows",
    colors: [
      "0078d7",
      "002050",
      "ffb900",
      "d83b01",
      "e81123",
      "b4009e",
      "5c2d91",
      "008272",
      "107c10",
    ],
    brand_url: "https://www.microsoft.com/windows/",
  },
  "windows-phone": {
    title: "Windows Phone",
    colors: ["68217a"],
    brand_url: null,
  },
  woocommerce: {
    title: "WooCommerce",
    colors: ["96588a", "3c3c3c", "71b02f"],
    brand_url: "https://woocommerce.com/",
  },
  wooga: { title: "Wooga", colors: ["5b009c"], brand_url: null },
  wordpress: {
    title: "WordPress",
    colors: ["21759b", "d54e21", "464646"],
    brand_url: null,
  },
  "wordpress-com": {
    title: "WordPress.com",
    colors: [
      "0087be",
      "78dcfa",
      "00aadc",
      "005082",
      "87a6bc",
      "f3f6f8",
      "e9eff3",
      "e9eff3",
      "a8bece",
      "668eaa",
      "4f748e",
      "3d596d",
      "2e4453",
      "d54e21",
      "f0821e",
      "4ab866",
      "f0b849",
      "d94f4f",
    ],
    brand_url: "https://wordpress.com/",
  },
  "world-organisation-of-the-scout-movement-wosm": {
    title: "World Organisation of the Scout Movement",
    colors: [
      "622599",
      "0054a0",
      "aaba0a",
      "dd7500",
      "e23d28",
      "3d8e33",
      "3399ff",
      "ff3399",
      "fcd116",
      "999999",
    ],
    brand_url: "http://scout.org/",
  },
  worldline: {
    title: "Worldline",
    colors: ["0066a1"],
    brand_url: "http://worldline.com",
  },
  wufoo: {
    title: "Wufoo",
    colors: ["e66760", "8c88cd", "69c5e4", "ffdf8b", "61e064"],
    brand_url: "http://www.wufoo.com/",
  },
  wunderlist: { title: "Wunderlist", colors: ["2b96f1"], brand_url: null },
  wwe: { title: "WWE", colors: ["d7182a"], brand_url: "http://www.wwe.com/" },
  "xavier-university": {
    title: "Xavier University",
    colors: ["0c2340", "9ea2a2", "0099cc"],
    brand_url: "https://www.xavier.edu/",
  },
  xbox: { title: "XBOX", colors: ["52b043"], brand_url: null },
  "xda-developers": {
    title: "XDA Developers",
    colors: ["f59714"],
    brand_url: "https://www.xda-developers.com/",
  },
  xing: { title: "XING", colors: ["026466", "cfdc00"], brand_url: null },
  "xy-gaming": {
    title: "XY Gaming",
    colors: ["3299cc", "333333"],
    brand_url: "http://xygaming.com/",
  },
  "y-combinator": {
    title: "Y Combinator",
    colors: ["ff4000"],
    brand_url: "https://www.ycombinator.com/",
  },
  yahoo: {
    title: "Yahoo!",
    colors: ["410093"],
    brand_url: "https://www.yahoo.com/",
  },
  yandex: { title: "Yandex", colors: ["ffcc00"], brand_url: null },
  "yellow-pages": {
    title: "Yellow Pages",
    colors: ["ffd400", "000000"],
    brand_url: "http://www.yellowpages.com/",
  },
  yelp: { title: "Yelp", colors: ["af0606"], brand_url: null },
  "yii-framework": {
    title: "Yii Framework",
    colors: ["d8582b", "16a314", "3b6fba"],
    brand_url: "http://www.yiiframework.com/",
  },
  yo: {
    title: "Yo",
    colors: [
      "9b59b6",
      "e74c3c",
      "8e44ad",
      "2980b9",
      "f1c40f",
      "16a085",
      "34495e",
      "3498db",
      "2ecc71",
      "1abc9c",
    ],
    brand_url: "http://www.justyo.co/",
  },
  youtube: {
    title: "YouTube",
    colors: ["ff0000", "282828"],
    brand_url: "https://www.youtube.com/",
  },
  yummly: {
    title: "Yummly",
    colors: ["e16120", "3a9691", "363533"],
    brand_url: "https://www.yummly.com/",
  },
  zapier: {
    title: "Zapier",
    colors: ["ff4a00", "fd7622", "ffc43e", "5f6c72", "499df3", "13d0ab"],
    brand_url: "https://zapier.com/",
  },
  zendesk: {
    title: "Zendesk",
    colors: [
      "00363d",
      "f79a3e",
      "eb6651",
      "30aabc",
      "eb4962",
      "37b8af",
      "78a300",
      "f0ca28",
    ],
    brand_url: "https://www.zendesk.com/",
  },
  zerply: { title: "Zerply", colors: ["9dbc7a"], brand_url: null },
  zillow: {
    title: "Zillow",
    colors: ["1277e1"],
    brand_url: "http://www.zillow.com/",
  },
  zomato: {
    title: "Zomato",
    colors: ["cb202d", "2d2d2d", "f4f4f2"],
    brand_url: "https://www.zomato.com/",
  },
  zoom: {
    title: "Zoom",
    colors: ["2d8cff", "f26d21"],
    brand_url: "https://zoom.us",
  },
  zopim: { title: "Zopim", colors: ["ff9d3b"], brand_url: null },
};
